/* Verified against ProviderSettingsDialog, provider-hub/api.rs and SecretaryDialog. */
window.MewApiGuide={
 protocols:[
  {id:'open_ai_responses',name:'OpenAI Responses',suffix:'/responses',endpoint:'https://api.example.com/v1/responses'},
  {id:'open_ai_chat_completions',name:'OpenAI Chat Completions',suffix:'/chat/completions',endpoint:'https://api.example.com/v1/chat/completions'},
  {id:'anthropic_messages',name:'Anthropic Messages',suffix:'/messages',endpoint:'https://api.example.com/v1/messages'}
 ],
 zh:{
  title:'接入你选择的 AI。',lead:'先验证 API，再分别用于会话总结和 AI 对话。配置、数据流向和常见问题，都在这里。',modes:['摘要总结','AI 对话'],tabs:['逐步配置','字段与协议','常见问题'],step:'步骤',previous:'上一步',next:'下一步',stepOf:'配置路线',read:'配置说明',watch:'查看演示',native:'配置与使用演示',nativeHint:'真实组件 · 模拟资料 · 不发送模型请求',openNative:'放大配置窗口',download:'下载完整指南',noSecret:'请在软件内填写真实密钥。本页只展示虚构配置，不接收真实 API Key。',protocol:'选择协议示例',fieldsTitle:'每个字段应该填什么',endpointTitle:'这个示例将使用的请求地址',endpointHint:'此处 example.com 和 your-model-id 都是占位符；请替换为服务商提供的真实服务地址及精确模型 ID。',copy:'复制无密钥示例',copied:'已复制示例',copyFailed:'请手动复制下方示例',demoStart:'播放配置流程',demoStop:'暂停演示',demoRestart:'从头演示',demoStatus:['准备填写配置','填写服务与模型','演示验证过程','演示验证成功','分别选用于摘要 / 聊天'],demoDisclaimer:'演示成功是流程说明，不代表你的 API 已连接。实际软件会发送测试消息，可能产生服务商费用。',focusLabels:['服务配置','名称 / Base URL / 模型 / 密钥','验证并保存','验证通过后仍需选用','摘要与对话分别选择'],referenceNote:'保存 API 不会自动切换摘要执行器；在聊天中选模型，也不会替换当前摘要设置。',localAlternative:'也可以选择本机 Agent',localText:'在会话总结助手中选“使用本地智能助手”，按查找 → 真实验证 → 选用操作。它与 API 是两条独立配置路线。聊天助手当前支持经过适配的 Codex / Claude Code；并非所有可归档来源都能用作聊天执行器。本机 Agent 也可能调用自己的云模型。',manageTitle:'修改、换密钥或停用',manageText:'在已验证服务列表点击“编辑”，修改后重新验证。编辑时 API Key 留空会沿用本机原凭据；填写新 Key 才会替换。验证失败不会覆盖原配置。删除服务前先为摘要或聊天更换提供方；需要彻底撤销密钥时，到原服务商控制台撤销。',
  workflows:[
   [
    {title:'准备服务',caption:'准备你自己的模型服务',body:'在所选服务商或自建网关取得 Base URL、API Key、精确模型 ID 和受支持的协议。确认账号余额、权限及模型可用性。',points:['MewMent 免费使用；模型服务的用量费用由服务商另收。','API 可以独立配置，无需先安装或验证本机 Agent。','选择第三方 API 后，摘要文本会发送给该服务商。'],visual:'prepare'},
    {title:'打开设置',caption:'进入“会话总结助手”',body:'在 MewMent 主窗口打开设置，找到“AI 会话时间归档”，进入“会话总结助手（智能助手 / API）”，选择“添加 API 摘要服务”。',points:['已有 API 配置可在已验证服务列表中编辑或重新验证。','“会话来源”负责找到记录，API 执行器负责生成摘要，两者分别设置。'],visual:'open'},
    {title:'填写配置',caption:'填写名称、协议、地址、模型和密钥',body:'名称用于自己辨认；协议应与服务商一致。Base URL 填服务基础地址，模型填写精确 ID，API Key 只在软件内输入。',points:['标准 /v1 接口通常无需填写 Endpoint 覆盖。','非标准路径在“高级协议设置”中填写以 / 开头的完整路径。','Anthropic Messages 可按服务商要求填写 Anthropic Version。'],visual:'fields'},
    {title:'验证保存',caption:'点击“验证并保存”',body:'软件向填写的服务发送一条随机测试消息，收到正确模型回复后才保存配置。仅 HTTP 成功、连通地址或收到错误页，都不等于验证通过。',points:['测试可能消耗服务商额度。','密钥保存到本机系统凭据库，界面仅显示掩码。','失败时查看错误，再按“常见问题”检查，避免反复盲试。'],visual:'verify'},
    {title:'选用于摘要',caption:'明确选用已验证的 API',body:'在已验证服务列表中点击“用作会话总结助手”，或者在“当前会话总结助手”中选择它，确认界面显示正在使用该服务。',points:['验证并保存 ≠ 已经切换。','不同摘要服务可以保留在列表中，但当前摘要执行器要明确选定。','在 AI 对话里选择另一模型，不会替你更改摘要选择。'],visual:'select'},
    {title:'选择来源',caption:'勾选要整理的本地会话',body:'回到“会话来源与自动整理”，开启需要的来源并保存设置，再点击“立即扫描”。标准目录会自动检测，自定义安装或特殊 WSL 位置可补充路径。',points:['支持整理 Codex、Claude Code、OpenCode、OpenClaw、Hermes、Pi 等来源。','API 配置正确，不等于电脑上已经存在可扫描的会话。','仅启用的来源会进入扫描；摘要需要可处理的新内容。'],visual:'sources'},
    {title:'检查结果',caption:'在 AI 日程里核对内容和时间',body:'切换到 AI 视角，展开会话记录，核对摘要、原始位置、日期与活动时间。它们用于回顾哪天做了什么、花了多久。',points:['摘要解释协作内容；时长以来源证据为依据。','不同来源可能显示精确计时或推断计时。','无新消息时，不应重复调用模型生成相同摘要。'],visual:'result'}
   ],
   [
    {title:'准备服务',caption:'准备能对话和调用工具的模型',body:'准备 Base URL、API Key、模型 ID 与协议。普通对话需要文本能力，聊天式任务管理还需要服务和模型兼容所选协议的工具调用。',points:['聊天与摘要可共用配置，也可选择不同服务。','确认模型/API 用量由你与服务商单独结算。','“本地软件”不代表所选模型一定离线运行。'],visual:'prepare'},
    {title:'添加 API',caption:'从 AI 助手进入模型/API 设置',body:'点击主窗口左上角的猫咪 Logo 打开 AI 助手，使用模型区域的设置按钮进入“添加模型 API”。也可以复用已经验证过的 API 条目。',points:['填写字段与摘要配置相同。','这里接入的是软件内聊天模型，不是对外提供的 MewMent MCP 接口。'],visual:'open'},
    {title:'验证保存',caption:'先确认真实回复，再保存',body:'填写服务名称、协议、Base URL、模型 ID 和 API Key，点击“验证并保存”。成功后返回 AI 助手；验证失败则检查地址、密钥、额度和协议。',points:['新增必须提供 Key；编辑时留空可复用本机凭据。','摘要选择与聊天选择独立；保存配置不会替你决定两个用途。'],visual:'verify'},
    {title:'选择模型',caption:'在对话中选择提供方和模型',body:'在助手的提供方下拉框选择已验证服务，再选择模型。可刷新模型列表；服务未提供模型目录时，可使用“自定义模型 ID”。',points:['使用服务商给出的精确 ID，不能只填展示名称。','配置改变后按软件提示新建对话，以使用新的服务配置。','思考等级等选项仅在对应模型支持时出现。'],visual:'select'},
    {title:'开始对话',caption:'先问候，再尝试一个明确的安排',body:'先发送一句简单问候确认可回复，再尝试“帮我为明天安排 30 分钟整理资料”。检查生成的任务、日期和执行结果。',points:['真实请求会发给你选择的服务商。','日程管理过程中，重要操作遵循授权和确认流程。','主助手与悬浮聊天共用当前会话。'],visual:'chat'},
    {title:'维护配置',caption:'按需要切换、编辑与撤销',body:'在助手中选择另一提供方，或回设置编辑服务并重新验证。遇到错误先检查密钥权限、额度、协议和工具调用兼容性。',points:['不要在网站或反馈邮件中发送完整 Key。','删除本机配置不等于在服务商处撤销密钥。','聊天正常但不能改日程时，检查工具调用支持及操作授权。'],visual:'manage'}
   ]
  ],
  shortSteps:[['准备','入口','填写','验证','选用','来源','结果'],['准备','添加','验证','选用','对话','维护']],
  fields:[['名称','便于识别的服务名称，如“我的摘要服务”。'],['协议模式','选择服务商支持的 Responses、Chat Completions 或 Anthropic Messages；不能仅按模型品牌猜测。'],['Base URL / 服务地址','填服务基础地址，例如 https://api.example.com/v1；不要填聊天网页地址、完整 /chat/completions 路由，或含密钥/查询参数的 URL。'],['模型','服务商提供的精确模型 ID；须有使用权限。示例 your-model-id 不能直接使用。'],['API Key / 访问密钥','在软件内填写服务商密钥。新建必填；编辑留空保留旧密钥。只写入本机系统凭据库。'],['Endpoint 路径覆盖','通常留空。若服务不是标准路径，填写从站点根开始的路径，如 /chat/completions 或 /v1/messages；它替换路径，不追加到 Base URL；不能含 ? 或 #。'],['Anthropic Version','仅 Anthropic Messages 使用；默认 2023-06-01，若网关要求其他值，按服务商说明填写。']],
  routing:'不填 Endpoint 覆盖时，Base URL 路径以 /v1 结尾会直接追加协议路径；只有域名时会补 /v1；其他前缀会追加 /v1 再加协议路径。远程服务必须使用 HTTPS，HTTP 仅允许 localhost、127.0.0.1 或 ::1。',
  faqs:[['401 / 403：密钥或权限错误','检查 Key 是否有效、是否粘贴完整、账号是否允许使用该模型；确认 Key 与 Base URL 属于同一服务。不要把网页登录密码当作 API Key。'],['404：找不到接口','检查协议是否被服务商支持，Base URL 是否重复包含 /v1 或完整接口后缀。非标准接口使用 Endpoint 路径覆盖。'],['429、余额不足或限流','查看服务商余额、额度和速率限制，等待后重试。MewMent 免费使用，但不提供第三方模型额度。'],['能连上但验证仍失败','服务必须返回正确的随机测试内容；错误页面、空回复、截断输出或不兼容协议都可能失败。检查模型和网关兼容性。'],['已经保存，但没有生成摘要','先显式选用“当前会话总结助手”，再启用来源、保存设置并扫描。检查本机是否有近期可处理会话；没有新增消息时可能不会再次摘要。'],['API 能聊天，但不能管理日程','检查模型及网关的工具调用支持、所选协议和应用中的授权提示。简单文本回复验证不保证所有工具操作可用。'],['本机 Agent 没有被发现','先确认工具已安装、登录并能自行工作；重新查找，必要时补充安装位置或 WSL 路径。归档来源与摘要执行器需要分别配置。'],['修改密钥或配置以后怎么办','编辑后重新验证；留空 Key 会沿用旧凭据。服务地址或协议变化时按提示新建对话。撤销泄露密钥应在原服务商控制台完成。']]
 },
 en:{
  title:'Connect your AI.',lead:'Verify an API, then select it separately for summaries and conversations. Follow the setup, understand the data flow, and resolve common errors.',modes:['Session summaries','AI conversations'],tabs:['Step by step','Fields & protocols','Troubleshooting'],step:'Step',previous:'Back',next:'Next',stepOf:'Setup route',read:'Instructions',watch:'View demo',native:'Setup & use demonstration',nativeHint:'Real components · Fictional data · No model requests',openNative:'Enlarge configuration',download:'Download full guide',noSecret:'Enter real credentials inside MewMent. This page only shows fictional values and does not accept real API keys.',protocol:'Protocol example',fieldsTitle:'What goes in each field',endpointTitle:'Resulting endpoint for this example',endpointHint:'example.com and your-model-id are placeholders. Replace them with your provider’s actual base address and exact model ID.',copy:'Copy key-free example',copied:'Example copied',copyFailed:'Please copy the example below manually',demoStart:'Play setup walkthrough',demoStop:'Pause walkthrough',demoRestart:'Restart',demoStatus:['Prepare the configuration','Enter the service and model','Demonstrate verification','Demonstration: verification passed','Select separately for summaries / chat'],demoDisclaimer:'Demonstration success explains the flow; it does not connect your API. The real app sends a test message, which may incur provider charges.',focusLabels:['Service configuration','Name / Base URL / Model / Key','Verify and save','Verification still needs a selection','Select summaries and chat independently'],referenceNote:'Saving an API does not change the summary provider automatically. Selecting a chat model does not replace your summary settings.',localAlternative:'You can use a local Agent, too',localText:'Choose a local assistant in summary settings, then Find → Verify → Select. This is independent of API setup. Chat currently supports adapted Codex / Claude Code providers; not every session source is a chat provider. A local Agent may still use its own cloud model.',manageTitle:'Edit, replace a key, or stop using a service',manageText:'Edit a verified entry and verify it again. Leaving API Key empty when editing keeps the existing local credential; a new key replaces it. Failed verification does not overwrite the original configuration. Select another provider before removing one in use. Revoke a key through its original provider when needed.',
  workflows:[
   [
    {title:'Prepare',caption:'Bring your own model service',body:'Get the Base URL, API key, exact model ID and supported protocol from your provider or self-hosted gateway. Check your balance, permissions and model access.',points:['MewMent is free to use; your model provider bills its own usage.','An API can be configured without installing or verifying a local Agent.','Summary text is sent to the provider you choose.'],visual:'prepare'},
    {title:'Open settings',caption:'Open the session summary assistant',body:'Open Settings in MewMent, find AI session time archiving, open the session summary assistant, and choose Add summary API.',points:['Existing entries can be edited or verified again.','Session sources locate records; the API provider generates summaries. Configure both.'],visual:'open'},
    {title:'Enter fields',caption:'Name, protocol, address, model and key',body:'Use a recognizable name. Select the protocol your provider supports, enter its base address and exact model ID, and enter the API key inside the app.',points:['Standard /v1 endpoints usually need no override.','Use Advanced protocol settings for a nonstandard absolute endpoint path.','Set Anthropic Version if your Messages provider requires it.'],visual:'fields'},
    {title:'Verify & save',caption:'Verify an actual model reply',body:'Choose Verify and save. The app sends a random test message and saves the configuration only after receiving the correct reply. A successful HTTP status alone is not sufficient.',points:['The test may consume provider credits.','Keys go into the local operating-system credential store; the UI shows a mask.','Check the error before repeatedly retrying.'],visual:'verify'},
    {title:'Select for summaries',caption:'Explicitly choose the verified API',body:'Click “Use as conversation assistant” on the verified summary-provider entry, or choose it as the current summary assistant. Confirm the displayed active provider.',points:['Verified and saved does not mean selected.','You may keep several providers, but choose the current summary provider explicitly.','Selecting a different chat model does not change this choice.'],visual:'select'},
    {title:'Select sources',caption:'Choose which local sessions to organize',body:'Open session sources and automatic organization, enable the sources you need, save, then Scan now. Standard locations are detected; add paths for custom installations or unusual WSL layouts.',points:['Sources include Codex, Claude Code, OpenCode, OpenClaw, Hermes and Pi.','A valid API does not create local sessions to scan.','Only enabled sources are scanned, and summaries need eligible content.'],visual:'sources'},
    {title:'Review results',caption:'Review the work and its time evidence',body:'Switch to the AI perspective and expand a session. Check its summary, original location, dates and activity time to understand what happened and how long it took.',points:['Summaries explain the work; time comes from source evidence.','Different sources may report exact or inferred time.','No new messages should mean no repeated summary call for the same content.'],visual:'result'}
   ],
   [
    {title:'Prepare',caption:'Choose a model for conversation and tools',body:'Prepare your Base URL, API key, model ID and protocol. Conversation needs text generation; schedule management also needs compatible tool calling from the model and gateway.',points:['Chat and summaries can share a configuration or use different providers.','You pay your provider separately for model/API usage.','A local app does not make every chosen model offline.'],visual:'prepare'},
    {title:'Add an API',caption:'Open model/API settings from the assistant',body:'Click the cat logo at the top left to open the AI assistant. Use the settings button beside its model controls to add a model API, or reuse an existing verified entry.',points:['The configuration fields are the same as for summaries.','This connects the in-app model; it is not the external MewMent MCP interface.'],visual:'open'},
    {title:'Verify & save',caption:'Verify a real reply before saving',body:'Enter the service name, protocol, Base URL, model ID and API key, then Verify and save. Return to the assistant after success; check the address, key, balance and protocol after failure.',points:['A new entry requires a key; editing with an empty key retains the local credential.','Summary and chat selections remain independent.'],visual:'verify'},
    {title:'Select a model',caption:'Choose the provider and model in chat',body:'Select the verified provider in the assistant, then choose a model. Refresh the model list when needed, or enter a custom model ID when no catalog is available.',points:['Use the exact model ID from the provider.','Start a new conversation when prompted after service configuration changes.','Reasoning controls appear only for supported models.'],visual:'select'},
    {title:'Start chatting',caption:'Say hello, then try one clear request',body:'Send a short greeting to check the reply. Then try “Plan 30 minutes tomorrow for organizing my notes.” Review the task, date and operation result.',points:['Real requests go to your chosen provider.','Important changes follow the app’s authorization and confirmation flow.','The full assistant and floating chat share the current conversation.'],visual:'chat'},
    {title:'Maintain',caption:'Switch, edit and revoke when necessary',body:'Choose another provider in chat, or edit and re-verify the configuration. Check key permissions, quota, protocol and tool compatibility when an operation fails.',points:['Do not send full keys through this website or feedback emails.','Removing local configuration does not revoke the provider’s key.','If chat works but task changes do not, check tool support and app authorization.'],visual:'manage'}
   ]
  ],
  shortSteps:[['Prep','Open','Fill','Test','Use','Scan','View'],['Prep','Add','Test','Pick','Chat','Edit']],
  fields:[['Name','A recognizable label, such as “My summary service”.'],['Protocol','Choose Responses, Chat Completions or Anthropic Messages according to the provider, not just the model brand.'],['Base URL / Service address','Use the service base address, such as https://api.example.com/v1. Do not use the chat website, a full /chat/completions route, or a URL containing credentials or query parameters.'],['Model','The provider’s exact model ID with the necessary permissions. The placeholder your-model-id is not a working model.'],['API Key','Enter the provider’s key inside the app. Required for new entries; leave empty when editing to retain the old key. Stored in the local OS credential store.'],['Endpoint path override','Usually empty. For a nonstandard route, use an absolute path such as /chat/completions or /v1/messages. It replaces the path instead of appending to the Base URL and must not contain ? or #.'],['Anthropic Version','Only for Anthropic Messages. Defaults to 2023-06-01; use another value only if required by your gateway.']],
  routing:'Without an override, a base path ending in /v1 gets the protocol suffix appended. A bare domain gets /v1 first; other prefixes get /v1 plus the suffix. Remote services must use HTTPS. HTTP is allowed only for localhost, 127.0.0.1 or ::1.',
  faqs:[['401 / 403: invalid key or permissions','Check that the key is valid, complete and authorized for this model, and belongs to the same service as the Base URL. A website password is not an API key.'],['404: endpoint not found','Check protocol support and duplicated /v1 or full endpoint suffixes in Base URL. Use an endpoint override for nonstandard routes.'],['429, insufficient credit or rate limits','Check the provider’s balance, quota and rate limits; wait before retrying. Free access to MewMent does not include third-party model credits.'],['The endpoint responds, but verification fails','The service must return the requested random test content. Error pages, empty or truncated replies and incompatible protocols can fail the check.'],['The API is saved, but summaries do not appear','Explicitly select it as the current summary assistant, enable sources, save and scan. Check for recent eligible local sessions. No new messages may mean no new summary request.'],['Chat works, but schedule changes do not','Check model and gateway tool-calling support, the selected protocol and app authorization prompts. A basic text reply does not prove every tool operation works.'],['A local Agent is not discovered','Make sure it is installed, signed in and working independently. Search again and add installation or WSL paths when needed. Session sources and summary providers are configured separately.'],['What happens after changing a key or configuration?','Edit and re-verify. An empty key keeps the existing credential. Start a new conversation when prompted after changing the service. Revoke compromised keys through the provider’s console.']]
 }
};

window.MewApiGuide.zh.demoDisclaimerShort='仅示意流程，不会连接 API。软件内验证可能产生模型费用。';
window.MewApiGuide.en.demoDisclaimerShort='Demo only; no API request. In-app verification may incur model fees.';
