/* Bilingual interface copy. Creator chapters are in narrative.js. */
window.MewContent = {
  "zh": {
    "title": "MewMent 开发故事 · 计时、日程与本地 AI 协作记录",
    "description": "从一个计时器开始：为什么把本人工作、本地 AI 会话、甘特图、时间统计和 Project 组织在 MewMent 里。创作者的开发故事与真实软件演示。",
    "nav": [
      "开发缘起",
      "任务计时",
      "本地 AI 会话",
      "甘特与统计",
      "Project",
      "聊天式管理",
      "猫咪伙伴"
    ],
    "navShort": [
      "缘起",
      "计时",
      "AI",
      "进度",
      "项目",
      "聊天",
      "猫咪"
    ],
    "navLabel": "开发故事与软件功能",
    "story": "创作者手记",
    "watch": "看看它的日常",
    "lang": "切换为英文",
    "motion": "暂停动画",
    "resumeMotion": "恢复动画",
    "homeEyebrow": "CREATOR’S JOURNAL / 从计时器开始",
    "homeTitle": "我想知道，<br>一天的时间<span>去了哪里。</span>",
    "homeBody": "一会儿与 AI 对话，一会儿动手工作，我的时间越来越碎。<br>MewMent 从一个计时器开始，把本人工作、本地 AI 协作与项目进度，慢慢放回同一个地方。",
    "explore": "从计时器开始",
    "demo": "先看完整软件",
    "catHello": "喵，它是这样一点点做出来的。",
    "catPet": "摸摸小墨",
    "catHint": "试着摸摸我",
    "timerLabel": "开发的起点：把工作记下来",
    "timerTask": "整理数据与验证结果",
    "timerStart": "开始",
    "timerPause": "暂停",
    "timerResume": "继续",
    "noteLabel": "当时的困扰",
    "noteText": "忙了一天，究竟推进了什么？",
    "noteFooter": "我想把这些投入看清楚。",
    "memoryLabel": "AI 协作，也要计入日程",
    "memoryText": "哪一天、做了什么、花了多久。",
    "footer": "从一次计时，到完整的工作记录。",
    "keyboard": "← → 阅读下一章",
    "scene": "场景",
    "close": "关闭",
    "actual": "看看软件里的样子",
    "demoTag": "互动示意 · 试试看",
    "reset": "重置演示",
    "learnMore": "这一幕的故事",
    "dayModes": [
      "任务",
      "甘特",
      "统计"
    ],
    "week": [
      "一",
      "二",
      "三",
      "四",
      "五",
      "六",
      "日"
    ],
    "dayNames": [
      "星期一 · 9 月 21 日",
      "星期二 · 9 月 22 日",
      "星期三 · 9 月 23 日",
      "星期四 · 9 月 24 日",
      "星期五 · 9 月 25 日",
      "星期六 · 9 月 26 日",
      "星期日 · 9 月 27 日"
    ],
    "dayTasks": [
      "完成数据分析与结果验证",
      "整理图表与方法笔记",
      "准备下一轮实验方案"
    ],
    "completeTask": "标记完成",
    "restoreTask": "恢复任务",
    "complete": "已经完成",
    "waiting": "等待开始",
    "inProgress": "正在投入",
    "focusTime": "这一次投入",
    "historySegments": "每一次开始，都在同一个任务里。",
    "taskCount": "件小事",
    "ganttTitle": "计划与真实，放在一起看",
    "planned": "计划",
    "recorded": "实际投入",
    "ganttHint": "点一下任务，看见它的每一段投入。",
    "segments": [
      "第一段 · 理清思路 · 09:00—09:40",
      "第二段 · 写下方案 · 10:15—11:10",
      "第三段 · 回来完善 · 14:00—14:25"
    ],
    "statsTitle": "这一周，你把时间给了什么？",
    "statsNote": "看清本人工作与 AI 协作的投入，安排下一步。",
    "statsCategories": [
      "分析与执行",
      "资料与学习",
      "与 AI 协作"
    ],
    "statsTotal": "已记录的投入",
    "statsUnit": "小时",
    "aiHint": "按日期回顾 AI 工作，并纳入甘特与时间统计。",
    "aiLocal": "可同时接入的本地 Agent 来源",
    "aiArchive": "MewMent · 本地 AI 工作记录",
    "aiStatus": "已整理",
    "aiSessionTitle": "分析方案讨论与结果复核",
    "aiSummaryTitle": "这段 AI 协作做了什么",
    "aiSummary": "讨论分析方案，排查异常样本，并整理验证结论。摘要与会话来源、日期和时间信息一起保存，供当天及项目回顾。",
    "aiNextTitle": "原始会话在哪里",
    "aiNext": "保留 Agent 名称与工作区线索，回看这段投入时可以找到来源。",
    "aiOpen": "查看这段协作的摘要",
    "aiCollapse": "收起摘要",
    "aiPrivacy": "先配置本地会话来源，再选择负责摘要的 Agent 或自定义 API。",
    "aiTime": "2026-09-24 · 3 段活动",
    "aiEvidence": "摘要说明协作内容；日期和时长按来源记录整理。",
    "projectRoot": "星河研究计划",
    "projectPhases": [
      "准备 · 明确问题",
      "执行 · 分析验证",
      "交付 · 复盘分享"
    ],
    "projectTasks": [
      [
        "梳理研究问题与输入资料",
        "今天的任务：整理数据与检查质量"
      ],
      [
        "完成分析与结果验证",
        "今天的任务：复核结果与补充实验"
      ],
      [
        "整理成果并分享进度",
        "今天的任务：准备图表与项目报告"
      ]
    ],
    "projectArrange": "自动排列",
    "projectHint": "交互示意 · 拖动节点，或聚焦后用方向键移动",
    "projectSelected": "当前阶段对应的每日任务",
    "projectProgress": "阶段进度",
    "projectDone": "做完这一步",
    "projectUndo": "重新打开",
    "projectLeaf": "每日任务与执行记录",
    "catActions": [
      "摸摸头",
      "逗逗猫",
      "伸个懒腰",
      "一起发会儿呆"
    ],
    "catReplies": [
      "呼噜……被温柔对待，真好。",
      "咦？让我看看是什么在动。",
      "伸——今天也要照顾好自己。",
      "不用一直做什么。陪着就很好。"
    ],
    "catActivity": "来自 MewMent 的真实黑猫动作",
    "catFamily": "每一只猫，都有自己的可爱",
    "catFamilyBody": "11 种猫咪伙伴。在 MewMent 里，找到与你合拍的那一只。",
    "storyTitle": "一天很忙，<br>我却说不清时间去了哪里。",
    "storyP1": "我喜欢最大化时间利用率，也越来越深入地和 AI 协作。一会儿对话，一会儿做正式工作，时间被打碎了；很多会话散落在不同工作区，项目的全貌也越来越难把握。",
    "storyP2": "MewMent 从计时器记录开始。我把本地 AI 会话、摘要与时间信息也纳入日程，再让记录形成甘特图和统计；用 Project—目标—Task 组织每天的工作。功能复杂起来后，又加入 MCP 和聊天式管理。",
    "storyP3": "猫咪是我留给这个工具的一点私心。Mew 与 Moment 组成了名字，黑猫陪着我，把每一份投入记录得更明白。",
    "storyBelief": "知道做了什么、用了多久、项目走到哪里，再决定下一步。",
    "storyCta": "从第一项功能开始",
    "galleryTitle": "看看 MewMent 如何工作。",
    "gallerySubtitle": "真实产品界面与连续演示 · 使用模拟资料",
    "galleryLoop": "连续演示",
    "galleryStill": "静态画面",
    "galleryIndex": "演示",
    "replayDemo": "重新播放演示",
    "liveHint": "点击演示窗口，可暂停自动播放并亲手操作。",
    "galleryNames": [
      "悬浮聊天",
      "项目画布",
      "甘特与子任务",
      "猫咪动作",
      "完整日程",
      "悬浮计时",
      "时间统计",
      "本地 AI 会话",
      "甘特导出"
    ],
    "galleryCaptions": [
      "从小窗直接说出安排，协助管理任务、补录时间和整理项目。",
      "从 Project 到目标和任务，查看结构、拖动节点与自动排列。",
      "让计划、多段执行和子任务记录形成甘特图。",
      "我喜欢猫，也希望每天使用的工具有一点温度。",
      "这就是 MewMent：日历、任务、时间轴、甘特、统计与 Project。",
      "把当前任务的计时留在小窗里，继续做眼前的工作。",
      "按日期回顾投入、进度和时间利用率，包含本人工作与 AI 协作。",
      "聚合本地 Agent 会话，保留摘要、原始位置、日期与时间信息，纳入日程回顾。",
      "按时间范围导出 Excel 或 HTML，用于协作、汇报和个人复盘。"
    ],
    "fullSize": "查看原尺寸图片",
    "imageError": "这段演示未能加载，请重新打开网页。"
  },
  "en": {
    "title": "The story of MewMent · Time, tasks and local AI collaboration",
    "description": "How a timer grew into MewMent: personal work, local AI sessions, Gantt charts, time utilization and projects. A creator’s journal with real product demonstrations.",
    "nav": [
      "The beginning",
      "Task timing",
      "Local AI work",
      "Gantt & statistics",
      "Projects",
      "Chat management",
      "Cat companions"
    ],
    "navShort": [
      "Story",
      "Tasks",
      "AI",
      "Time",
      "Plan",
      "Chat",
      "Cats"
    ],
    "navLabel": "Development story and product features",
    "story": "Creator’s journal",
    "watch": "A day with MewMent",
    "lang": "Switch to Chinese",
    "motion": "Pause motion",
    "resumeMotion": "Resume motion",
    "homeEyebrow": "CREATOR’S JOURNAL / IT STARTED WITH A TIMER",
    "homeTitle": "I wanted to know<br>where my <span>day went.</span>",
    "homeBody": "Between AI conversations and hands-on work, my day became fragmented.<br>MewMent began as a timer—and grew into one place for my work, local AI collaboration and project progress.",
    "explore": "Start with the timer",
    "demo": "See the whole app",
    "catHello": "Mew. Here’s how it all came together.",
    "catPet": "Pet Ink",
    "catHint": "A little pat?",
    "timerLabel": "Where it began: record the work",
    "timerTask": "Analyze data and validate results",
    "timerStart": "Start",
    "timerPause": "Pause",
    "timerResume": "Resume",
    "noteLabel": "The question I had",
    "noteText": "A busy day. What actually moved forward?",
    "noteFooter": "I wanted to understand that effort.",
    "memoryLabel": "AI work belongs in the agenda",
    "memoryText": "Which day. What happened. How long.",
    "footer": "From one timer to a record of the working day.",
    "keyboard": "← → to read the next chapter",
    "scene": "Scene",
    "close": "Close",
    "actual": "See the real app",
    "demoTag": "Interactive illustration · Try it",
    "reset": "Reset demo",
    "learnMore": "Behind this moment",
    "dayModes": [
      "Tasks",
      "Timeline",
      "Insights"
    ],
    "week": [
      "M",
      "T",
      "W",
      "T",
      "F",
      "S",
      "S"
    ],
    "dayNames": [
      "Monday · September 21",
      "Tuesday · September 22",
      "Wednesday · September 23",
      "Thursday · September 24",
      "Friday · September 25",
      "Saturday · September 26",
      "Sunday · September 27"
    ],
    "dayTasks": [
      "Analyze data and verify results",
      "Organize charts and method notes",
      "Plan the next experiment"
    ],
    "completeTask": "Mark complete",
    "restoreTask": "Reopen task",
    "complete": "Completed",
    "waiting": "Ready when you are",
    "inProgress": "In progress",
    "focusTime": "This stretch of time",
    "historySegments": "Every fresh start belongs to the same task.",
    "taskCount": "little things",
    "ganttTitle": "Plans and effort, side by side",
    "planned": "Planned",
    "recorded": "Recorded",
    "ganttHint": "Select a task to see the time that went into it.",
    "segments": [
      "First stretch · Find direction · 09:00–09:40",
      "Second stretch · Write it down · 10:15–11:10",
      "Third stretch · Refine it · 14:00–14:25"
    ],
    "statsTitle": "Where did your time go this week?",
    "statsNote": "Review personal and AI effort to decide what comes next.",
    "statsCategories": [
      "Analysis & work",
      "Research & learning",
      "With AI"
    ],
    "statsTotal": "Time remembered",
    "statsUnit": "hours",
    "aiHint": "Review AI work by date and include it in Gantt views and time statistics.",
    "aiLocal": "Local agent sources that can coexist",
    "aiArchive": "MewMent · Local AI work records",
    "aiStatus": "Organized",
    "aiSessionTitle": "Discuss the analysis and verify results",
    "aiSummaryTitle": "What this collaboration covered",
    "aiSummary": "Discuss the analysis, investigate unusual samples and record the conclusions. Keep the summary with its source, date and time information for daily and project review.",
    "aiNextTitle": "Where the original session is",
    "aiNext": "Retain the Agent and workspace context so the original conversation can be found when reviewing the work.",
    "aiOpen": "Read the collaboration summary",
    "aiCollapse": "Close summary",
    "aiPrivacy": "Configure local session sources, then choose an Agent or custom API to summarize them.",
    "aiTime": "2026-09-24 · 3 activity spans",
    "aiEvidence": "Summaries describe the work; source records provide dates and duration.",
    "projectRoot": "The Starfield project",
    "projectPhases": [
      "Prepare · Define",
      "Execute · Validate",
      "Deliver · Review"
    ],
    "projectTasks": [
      [
        "Frame the question and inputs",
        "Today: organize data and check its quality"
      ],
      [
        "Analyze and validate results",
        "Today: review findings and follow-up experiments"
      ],
      [
        "Share the results and progress",
        "Today: prepare figures and a project report"
      ]
    ],
    "projectArrange": "Arrange",
    "projectHint": "Interactive illustration · Drag a node or use arrow keys",
    "projectSelected": "Daily work under the selected goal",
    "projectProgress": "Phase progress",
    "projectDone": "Finish this step",
    "projectUndo": "Reopen",
    "projectLeaf": "Daily tasks and work records",
    "catActions": [
      "A gentle pat",
      "Let’s play",
      "A little stretch",
      "Just be here"
    ],
    "catReplies": [
      "Purr… kindness feels rather lovely.",
      "Oh? What’s that moving over there?",
      "Streeetch. Take care of yourself today.",
      "We don’t have to do anything. This is nice."
    ],
    "catActivity": "Original MewMent black cat animations",
    "catFamily": "Every cat has a little magic",
    "catFamilyBody": "11 cat companions. Find the one that feels like you in MewMent.",
    "storyTitle": "A busy day.<br>But where did the time go?",
    "storyP1": "I care about making the most of my time, and I work deeply with AI. Switching between conversations and hands-on work fragmented the day. Sessions were scattered across workspaces, and I was losing sight of the bigger project.",
    "storyP2": "MewMent started with a timer. I brought local AI sessions, summaries and time information into the agenda, let those records form Gantt charts and statistics, and organized daily work under a Project—Goal—Task tree. As the controls grew, I added MCP and chat-based management.",
    "storyP3": "The cats are a personal touch. Mew meets Moment in the name, and a black cat keeps me company while I make sense of the effort.",
    "storyBelief": "Know what happened, how long it took and where the project stands—then decide what comes next.",
    "storyCta": "Start with the first feature",
    "galleryTitle": "See how MewMent works.",
    "gallerySubtitle": "Real product interfaces and continuous demos · Fictional data",
    "galleryLoop": "Live demonstration",
    "galleryStill": "Still frame",
    "galleryIndex": "Demo",
    "replayDemo": "Replay this demo",
    "liveHint": "Click inside the demo to pause the tour and try it yourself.",
    "galleryNames": [
      "Floating chat",
      "Project canvas",
      "Task timeline",
      "Cat moments",
      "The full planner",
      "Floating timer",
      "Time statistics",
      "Local AI sessions",
      "Gantt export"
    ],
    "galleryCaptions": [
      "Say the plan in a small window: manage tasks, backfill time and organize projects.",
      "Inspect the project-goal-task structure, move nodes and arrange the graph.",
      "Let plans, multiple work sessions and subtasks form the Gantt chart.",
      "I love cats. A tool I use every day should have a little warmth.",
      "This is MewMent: calendar, tasks, timeline, Gantt, statistics and projects.",
      "Keep the current task’s timer nearby while you continue the work.",
      "Review effort, progress and time utilization, including personal work and AI collaboration.",
      "Collect local Agent sessions with summaries, original locations, dates and time information for agenda review.",
      "Export a date range to Excel or HTML for collaboration, reporting and personal review."
    ],
    "fullSize": "Open full-size image",
    "imageError": "This demo could not load. Please reopen the page."
  }
};
