window.MewFeatures=(()=>{
 let ui,state;
 const c=()=>MewExperience[state.lang];
 function init(context){ui=context;state=context.state;addEventListener('resize',mediaSync);document.addEventListener('visibilitychange',mediaSync);}
 function feature(){return c().features[state.feature];}
 function details(){return feature().details[state.featureScene]||feature().details[0];}
 function scene(){return feature().scenes[state.featureScene]?.[1]||'cats';}
 const posters={planner:'01-main-panorama.png',floating:'11-mini-chat.png',statistics:'10-statistics.png',project:'06-project-graph.png',gantt:'08-gantt-subtasks.png',export:'09-gantt-export.png',ai:'03-ai-multi-agent.png',sources:'03-ai-multi-agent.png',assistant:'11-mini-chat.png'};
 function media(){const prefix='Resource/media/'+(state.lang==='en'?'en/':'');return `<span class="workflow-media" data-width="824" data-height="1080"><img src="${prefix}23-chat-to-task-still.png" data-still="${prefix}23-chat-to-task-still.png" data-gif="${prefix}23-chat-to-task.gif" alt="${state.lang==='zh'?'输入安排，创建日程，再回到列表查看结果':'Describe a plan, create a task, then see it in the planner'}"></span>`;}
 function mediaSync(){document.querySelectorAll('.workflow-media').forEach(el=>{const p=el.parentElement,s=getComputedStyle(p),w=p.clientWidth-parseFloat(s.paddingLeft)-parseFloat(s.paddingRight),h=p.clientHeight-parseFloat(s.paddingTop)-parseFloat(s.paddingBottom);if(w>1&&h>1){const scale=Math.min(w/824,h/1080);el.style.width=824*scale+'px';el.style.height=1080*scale+'px';}const img=el.querySelector('img'),show=el.getBoundingClientRect().width>1&&el.getBoundingClientRect().height>1,covered=state.modal&&!el.closest('dialog[open]'),play=!state.paused&&!document.hidden&&show&&!covered,source=play?img.dataset.gif+(img.dataset.replay?'?replay='+img.dataset.replay:''):img.dataset.still;if(img.getAttribute('src')!==source)img.src=source;});}
 function product(){const s=scene();if(s==='workflow')return media();return MewDemo.frame({scene:s,lang:state.lang,title:feature().name,poster:'Resource/media/'+(state.lang==='en'?'en/':'')+posters[s]});}
 function controls(){const t=c(),f=feature();return `<div class="feature-scene-controls">${f.scenes.length>1?`<label class="mobile-scene-select"><span class="sr-only">${t.sceneSelect}</span><select data-feature-scene-select>${f.scenes.map(([label],i)=>`<option value="${i}" ${state.featureScene===i?'selected':''}>${label}</option>`).join('')}</select></label>`:''}<div class="feature-scene-tabs" role="group" aria-label="${t.sceneSelect}">${f.scenes.map(([label],i)=>`<button data-feature-scene="${i}" aria-pressed="${state.featureScene===i}">${label}</button>`).join('')}</div>${!['integration','mcp'].includes(scene())?`<button class="icon-button" data-action="product" aria-label="${t.expand}" title="${t.expand}">${ui.icon('expand')}</button>`:''}${scene()==='workflow'?`<button class="icon-button" data-workflow-replay aria-label="${t.restart}" title="${t.restart}">${ui.icon('reset')}</button>`:''}</div>`;}
 function article(){const t=c(),f=feature(),d=details();return `<article class="feature-copy"><h1>${f.name}</h1><p class="feature-description">${f.body}</p><section class="feature-actions"><h2>${t.labels.can}</h2><ul>${d.can.map(p=>`<li>${p}</li>`).join('')}</ul></section>${d.note.length?`<section class="feature-notes"><h2>${t.labels.note}</h2>${d.note.map(p=>`<p>${p}</p>`).join('')}</section>`:''}${f.setup!==undefined?`<button class="setup-link" data-setup="${f.setup}">${f.setup===0?t.setupSummary:t.setupChat}${ui.icon('arrow')}</button>`:''}<button class="mobile-watch primary-button" data-feature-pane="1">${t.view}${ui.icon('play')}</button></article>`;}
 function render(){const t=c(),f=feature();return `<div class="features-view" data-feature-kind="${f.id}"><aside class="feature-sidebar"><span>${t.nav[1]}</span><nav aria-label="${t.featureSelect}">${t.features.map((item,i)=>`<button data-feature="${i}" data-feature-kind="${item.id}" aria-current="${state.feature===i?'page':'false'}">${item.name}${state.feature===i?ui.icon('arrow'):''}</button>`).join('')}</nav><button class="sidebar-cat" data-feature="6"><img src="Resource/cats/calico.svg" alt="" width="90" height="90"><span>${t.features[6].name}</span></button></aside><label class="mobile-feature-select"><span class="sr-only">${t.featureSelect}</span><select data-feature-select>${t.features.map((item,i)=>`<option value="${i}" ${state.feature===i?'selected':''}>${item.name}</option>`).join('')}</select></label>
  ${state.feature===6?`<section class="feature-cats"><h1>${f.name}</h1><p>${f.body}</p>${MewHome.gallery()}</section>`:`<div class="feature-main" data-feature-pane="${state.featurePane}"><div class="feature-pane-switch" role="group" aria-label="${f.name}">${t.featuresMobile.map((label,i)=>`<button data-feature-pane="${i}" aria-pressed="${state.featurePane===i}">${label}</button>`).join('')}</div><div class="feature-intro">${article()}${controls()}</div><section class="feature-showcase" aria-label="${f.name}"><div class="feature-demo-space">${scene()==='integration'?integration():scene()==='mcp'?mcp():product()}</div></section></div>`}</div>`;}
 function integration(){const t=c(),n=state.projectPhase;return `<section class="integration-view" aria-label="${t.integrationTitle}"><div class="integration-project">${ui.icon('project')}<strong>${t.integrationProject}</strong></div><div class="integration-connect" aria-hidden="true"></div><div class="integration-phases" role="group" aria-label="${t.integrationHint}">${t.integrationGoals.map((v,i)=>`<button data-project-phase="${i}" aria-pressed="${n===i}">${v}</button>`).join('')}</div><div class="integration-detail"><div class="integration-tasks">${t.integrationTasks[n].map((v,i)=>`<div>${ui.icon('day')}<span>${v}</span><span class="integration-task-status">${i===0?ui.icon('check'):''}</span></div>`).join('')}</div><div class="integration-files"><strong>${t.integrationFolder}</strong>${t.integrationFiles[n].map(file=>`<div>${ui.icon('file')}<span>${file}</span></div>`).join('')}</div></div><p>${t.integrationHint}</p></section>`;}
 function mcp(){const t=c();return `<section class="mcp-view"><h2>${t.mcpTitle}</h2><div class="mcp-flow">${t.mcpSteps.map((v,i)=>`<div><span class="mcp-node">${ui.icon(['memory','link','day'][i])}</span><p>${v}</p></div>`).join('')}</div><blockquote>${t.mcpExample}</blockquote><p class="mcp-note">${t.mcpNote}</p></section>`;}
 function handle(button){const d=button.dataset;
  if(d.workflowReplay!==undefined){document.querySelectorAll('.workflow-media img').forEach(img=>img.dataset.replay=String(Date.now()));mediaSync();return true;}
  if(d.feature!==undefined){state.feature=Number(d.feature);state.featureScene=0;state.featurePane=0;ui.navigate(1,true);return true;}
  if(d.featureScene!==undefined){state.featureScene=Number(d.featureScene);ui.render(`[data-feature-scene="${state.featureScene}"]`);return true;}
  if(d.featurePane!==undefined){state.featurePane=Number(d.featurePane);document.querySelector('.feature-main').dataset.featurePane=String(state.featurePane);document.querySelectorAll('[data-feature-pane]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.featurePane)===state.featurePane)));MewDemo.sync();mediaSync();return true;}
  if(d.projectPhase!==undefined){state.projectPhase=Number(d.projectPhase);document.querySelector('.feature-demo-space').innerHTML=integration();document.querySelector(`[data-project-phase="${state.projectPhase}"]`).focus({preventScroll:true});return true;}
  if(d.setup!==undefined){state.guideMode=Number(d.setup);state.guideStep=0;state.guideTab=0;state.guidePane=0;ui.openDialog('guide');return true;}
  return false;
 }
 return{init,render,handle,product,feature,scene,mediaSync};
})();
