window.MewGuideUI=(()=>{
 let state,ui,timer=0;
 const g=()=>window.MewApiGuide[state.lang];
 const icon=name=>ui.icon(name);
 function init(context){ui=context;state=context.state;document.addEventListener('change',event=>{if(event.target.matches('[data-guide-select]')){state.guideStep=Number(event.target.value);ui.render('[data-guide-select]');}if(event.target.matches('[data-faq-select]')){state.faq=Number(event.target.value);ui.render('[data-faq-select]');}});addEventListener('message',event=>{const frame=[...document.querySelectorAll('.product-live-frame')].find(el=>el.contentWindow===event.source);if(frame&&event.data?.type==='mewment-demo-ready'&&event.data.scene==='api')sendFocus();});}
 function render(){
  const c=ui.copy(),t=g();
  return `<div class="api-heading"><a class="guide-download" href="Resource/Guides/API-setup.${state.lang==='zh'?'zh-CN':'en'}.md" download>${t.download}${icon('download')}</a></div>
  <div class="api-toolbar"><div class="api-tabs" role="tablist" aria-label="${t.title}">${t.tabs.map((label,i)=>`<button data-guide-tab="${i}" id="guide-tab-${i}" role="tab" aria-controls="guide-content" aria-selected="${state.guideTab===i}" tabindex="${state.guideTab===i?'0':'-1'}" class="${state.guideTab===i?'active':''}">${label}</button>`).join('')}</div></div>
  <section id="guide-content" class="api-content guide-tab-${state.guideTab}" role="tabpanel" aria-labelledby="guide-tab-${state.guideTab}">${[steps,fields,faq][state.guideTab]()}</section>`;
 }
 function steps(){
  const t=g(),items=t.workflows[state.guideMode],step=items[state.guideStep];
  return `<nav class="guide-steps" aria-label="${t.stepOf}">${items.map((item,i)=>`<button data-guide-step="${i}" aria-label="${t.step} ${i+1}: ${item.title}" title="${item.title}" aria-current="${state.guideStep===i?'step':'false'}" class="${state.guideStep===i?'active':''}"><span>${i+1}</span><strong>${item.title}</strong></button>`).join('')}</nav>
  <div class="mobile-step-bar"><label>${t.stepOf}<select data-guide-select>${items.map((item,i)=>`<option value="${i}" ${state.guideStep===i?'selected':''}>${i+1} / ${items.length} · ${item.title}</option>`).join('')}</select></label><div class="mobile-guide-toggle"><button data-guide-pane="0" aria-pressed="${state.guidePane===0}">${t.read}</button><button data-guide-pane="1" aria-pressed="${state.guidePane===1}">${t.watch}</button></div></div>
  <article class="guide-step-copy" data-active="${state.guidePane===0}"><div class="step-title"><span class="step-counter">${t.step} ${state.guideStep+1} / ${items.length}</span><h2>${step.caption}</h2></div><div class="step-reading"><p>${step.body}</p><ul>${step.points.map(point=>`<li>${point}</li>`).join('')}</ul><p class="guide-reference-note">${t.referenceNote}</p></div><div class="guide-step-navigation"><button data-guide-move="-1" ${state.guideStep===0?'disabled':''}>${t.previous}</button><button data-guide-move="1" ${state.guideStep===items.length-1?'disabled':''}>${t.next}${icon('arrow')}</button></div></article>
  <section class="guide-demonstration" data-config="${demoScene()==='api'}" data-active="${state.guidePane===1}"><div class="guide-demo-top"><div><strong>${t.native}</strong></div><button class="icon-button" data-action="api-native" aria-label="${t.openNative}">${icon('expand')}</button></div><div class="native-api-frame">${product()}</div><div class="guide-demo-bottom"><div class="guide-demo-controls"><button data-action="guide-play" ${state.paused?'disabled':''}>${icon(state.demoPlaying?'pause':'play')}${state.demoPlaying?t.demoStop:t.demoStart}</button><span class="guide-demo-status" aria-live="polite">${t.demoStatus[state.guideDemo]}</span><button data-action="guide-restart" ${state.paused?'disabled':''} aria-label="${t.demoRestart}">${icon('reset')}</button></div><div class="guide-demo-progress" aria-hidden="true">${t.demoStatus.map((_,i)=>`<i class="${i<=state.guideDemo?'active':''}"></i>`).join('')}</div><p class="demo-no-network">${t.demoDisclaimerShort}</p></div></section>`;
 }
 function demoScene(){const visual=g().workflows[state.guideMode][state.guideStep].visual;return visual==='result'?'ai':visual==='sources'?'sources':visual==='chat'?'floating':visual==='select'&&state.guideMode===1?'assistant':'api';}
 function product(){const scene=demoScene(),file=scene==='ai'||scene==='sources'?'03-ai-multi-agent.png':scene==='floating'||scene==='assistant'?'11-mini-chat.png':'22-model-api.png',poster='Resource/media/'+(state.lang==='en'?'en/':'')+file;return MewDemo.frame({scene,lang:state.lang,title:g().native,poster});}
 function fields(){const t=g(),p=window.MewApiGuide.protocols[state.protocol];return `<div class="api-fields-main"><h2>${t.fieldsTitle}</h2><div class="protocol-tabs" role="group" aria-label="${t.protocol}">${window.MewApiGuide.protocols.map((protocol,i)=>`<button data-protocol="${i}" aria-pressed="${state.protocol===i}" class="${state.protocol===i?'active':''}">${protocol.name}</button>`).join('')}</div><dl class="api-field-list">${t.fields.map(([name,detail])=>`<div><dt>${name}</dt><dd>${detail}</dd></div>`).join('')}</dl></div><aside class="api-example"><span class="eyebrow">${p.name}</span><h3>${t.endpointTitle}</h3><code class="endpoint-result">${p.endpoint}</code><pre id="api-config-example">${ui.escape(example())}</pre><button class="text-button" data-action="copy-config">${t.copy}${icon('check')}</button><p>${t.endpointHint}</p><p class="routing-note">${t.routing}</p><div class="key-storage-note">${t.noSecret}</div></aside>`;}
 function example(){const p=window.MewApiGuide.protocols[state.protocol];return JSON.stringify({displayName:state.lang==='zh'?'我的模型服务':'My model service',protocol:p.id,baseUrl:'https://api.example.com/v1',model:'your-model-id',endpointOverride:null,...(state.protocol===2?{anthropicVersion:'2023-06-01'}:{})},null,2);}
 function faq(){const t=g();return `<nav class="faq-list" aria-label="${t.tabs[2]}">${t.faqs.map(([title],i)=>`<button data-faq="${i}" aria-pressed="${state.faq===i}" class="${state.faq===i?'active':''}">${title}${icon('arrow')}</button>`).join('')}</nav><label class="mobile-faq-select">${t.tabs[2]}<select data-faq-select>${t.faqs.map(([title],i)=>`<option value="${i}" ${state.faq===i?'selected':''}>${title}</option>`).join('')}</select></label><article class="faq-answer"><h2>${t.faqs[state.faq][0]}</h2><p>${t.faqs[state.faq][1]}</p><div class="guide-related"><h3>${t.manageTitle}</h3><p>${t.manageText}</p><h3>${t.localAlternative}</h3><p>${t.localText}</p></div></article>`;}
 function sendFocus(){document.querySelectorAll('.native-api-frame iframe,.dialog-api-native iframe').forEach(frame=>frame.contentWindow?.postMessage({type:'mewment-api-demo-focus',phase:state.guideDemo},'*'));}
 function pause(){clearTimeout(timer);}
 function sync(){pause();sendFocus();if(state.demoPlaying&&!state.paused&&state.modal==='guide'&&state.guidePane===1&&state.guideTab===0&&demoScene()==='api'){timer=setTimeout(()=>{if(document.hidden){sync();return;}state.guideDemo=(state.guideDemo+1)%5;updateDemo();},1800);}}
 function updateDemo(){const t=g();document.querySelectorAll('.guide-demo-progress i').forEach((el,i)=>el.classList.toggle('active',i<=state.guideDemo));const label=document.querySelector('.guide-demo-status');if(label)label.textContent=t.demoStatus[state.guideDemo];const button=document.querySelector('[data-action="guide-play"]');if(button)button.innerHTML=icon(state.demoPlaying?'pause':'play')+(state.demoPlaying?t.demoStop:t.demoStart);sync();}
 function handle(button){const d=button.dataset;let changed=false,focus;
  if(d.guideMode!==undefined){state.guideMode=Number(d.guideMode);state.guideStep=0;focus=`[data-guide-mode="${state.guideMode}"]`;changed=true;}
  if(d.guideTab!==undefined){state.guideTab=Number(d.guideTab);focus=`[data-guide-tab="${state.guideTab}"]`;changed=true;}
  if(d.guideStep!==undefined){state.guideStep=Number(d.guideStep);focus=`[data-guide-step="${state.guideStep}"]`;changed=true;}
  if(d.guideMove!==undefined){state.guideStep=Math.min(g().workflows[state.guideMode].length-1,Math.max(0,state.guideStep+Number(d.guideMove)));focus=matchMedia('(max-width:760px)').matches?'[data-guide-select]':`[data-guide-step="${state.guideStep}"]`;changed=true;}
  if(d.guidePane!==undefined){state.guidePane=Number(d.guidePane);document.querySelector('.guide-step-copy').dataset.active=String(state.guidePane===0);document.querySelector('.guide-demonstration').dataset.active=String(state.guidePane===1);document.querySelectorAll('[data-guide-pane]').forEach(el=>el.setAttribute('aria-pressed',String(Number(el.dataset.guidePane)===state.guidePane)));MewDemo.sync();sync();return true;}
  if(d.protocol!==undefined){state.protocol=Number(d.protocol);focus=`[data-protocol="${state.protocol}"]`;changed=true;}
  if(d.faq!==undefined){state.faq=Number(d.faq);focus=`[data-faq="${state.faq}"]`;changed=true;}
  if(d.action==='guide-play'||d.action==='guide-restart'){if(d.action==='guide-restart'){state.guideDemo=0;state.demoPlaying=true;}else state.demoPlaying=!state.demoPlaying;updateDemo();return true;}
  if(d.action==='copy-config'){navigator.clipboard?.writeText(example()).then(()=>{button.textContent=g().copied;},()=>{button.textContent=g().copyFailed;});if(!navigator.clipboard)button.textContent=g().copyFailed;return true;}
  if(changed){ui.render(focus);return true;}return false;
 }
 return {init,render,product,handle,sync,pause};
})();
