/* Creator intent is sourced from the user's original MewMent development diary
 * request, not inferred from a generic productivity-brand narrative. */
window.MewNarrative = {
  zh: {
    readingTabs: ['开发故事', '功能与用法', '互动体验'],
    next: '接下来', outcome: '我想解决的是', demoHint: '右侧可以直接体验；实景使用模拟资料。',
    productDefinition: 'MewMent · Windows 侧边日程与本地 AI 协作记录',
    homePreview: '打开 MewMent 完整软件演示', homePreviewCaption: '这是 MewMent：日历、任务与执行记录在同一个窗口',
    homeBridge: '它从一个计时器开始，后来长出了这些功能。',
    featuresLabel: '这一章的功能', sourceNote: '创作者手记 · 从实际工作中的问题出发',
    aiDate: '发生在哪天', aiDuration: '当天 AI 协作', aiSource: '保留来源', aiEffort: '55 分钟',
    aiRecordLabel: '示例 · 2026 年 9 月 24 日', aiActivity: '3 段活动 · 20 + 25 + 10 分钟',
    aiDestinations: ['按日期看 AI 日程', '纳入甘特图', '计入时间统计'],
    aiFlow: ['本地会话与原始位置', '内容摘要 + 时间记录', '日程、甘特与统计'],
    aiScope: '可同时接入多个来源。这里点选来源，仅切换下方的示例。',
    insightModes: ['甘特与导出', '时间利用率'],
    insightGanttCaption: '计划、真实执行、完成时点，来自已有记录。',
    insightStatsCaption: '按日、周、月回顾，比较本人工作与 AI 协作投入。',
    exportNote: '导出 Excel / HTML，给同事、上司，也给以后复盘的自己。',
    exportButton: '看看导出设置',
    assistantModes: ['悬浮聊天', '外部 Agent / MCP', '自定义模型'],
    assistantCaption: '小窗与完整助手共用会话，随手说出安排。',
    mcpTitle: '让常用的 Agent 也能管理日程',
    mcpInput: '“把星河计划下周要做的事，整理成任务。”',
    mcpSteps: ['外部 AI Agent', 'MewMent MCP', '任务 / 项目 / 时间记录'],
    mcpActions: ['查询与新建任务', '调整计划与项目', '记录与补录时间'],
    mcpNote: '通过软件提供的受控工具操作，重要操作遵循授权与确认流程。',
    modelCaption: '会话摘要与聊天管理可以分别选择 Agent 或自定义 API。',
    chapters: [
      { eyebrow:'CREATOR’S JOURNAL / 为什么开始', title:'我想知道，<br>一天的时间<span>去了哪里。</span>',
        story:['我喜欢把时间用得充分，也越来越深入地与 AI 协作。一会儿讨论方案，一会儿动手工作，时间却散成了许多碎片。','于是，我从一个计时器开始做 MewMent：记下自己做过的事，也把本地 AI 协作放回同一张日程。'],
        features:[['记录工作','任务、子任务、多段计时与补录。'],['看清投入','本地 AI 会话、甘特图与时间利用率。'],['推进项目','Project 目标树，以及聊天式日程管理。']],
        result:'忙了一天，能说清做了什么、用了多久、项目走到了哪里。', next:'先把真正做过的工作记下来', gallery:4 },
      { eyebrow:'01 / 从计时器开始', title:'先记下，<br>我<span>真正做过</span>的事。',
        story:['最早，我只是想要一个顺手的计时器。准备做事时开始，被打断时暂停，回来后继续；一天里的零碎投入，应该留在同一项任务里。','有了这些真实记录，计划、任务、子任务和日历才慢慢接在一起。忘记打开计时，也可以补录。'],
        features:[['Task 与子任务','记录名称、计划、颜色、完成情况，并向下拆分。'],['多段执行与补录','同一任务可多次开始、暂停，保留每一段实际投入。'],['日程与悬浮计时','在日历安排日期，用每日时间轴对照计划和执行；小窗显示当前计时及倒计时。']],
        result:'把“今天很忙”变成可回顾的任务和时间记录。', next:'但与 AI 协作的时间，还没有算进来', gallery:4 },
      { eyebrow:'02 / 把 AI 协作纳入日程', title:'和 AI 做的工作，<br>也应该<span>有时间记录。</span>',
        story:['我常在几个本地 Agent 和工作区之间切换。只记录自己动手的工作，还说不清哪天与 AI 做了什么、投入多久；过后也很难把分散的会话找齐。','所以我加入本地会话整理与自动摘要：集中保留来源、协作内容、日期和时间信息，让这部分工作进入日程、甘特和时间统计。'],
        features:[['聚合本地会话','可整理 Codex、Claude Code、OpenCode、OpenClaw、Hermes、Pi 等来源，保留工具与工作区线索。'],['内容和时间各有依据','摘要说明这段协作做了什么；日期、活动段和时长依据各来源能提供的记录整理。'],['回到同一张工作记录','按日期查看本人工作与 AI 协作，回顾投入与进度，也能找到原始会话。']],
        result:'具体哪一天，花了多久与 AI 对话或协作，这些投入不再漏在日程之外。', next:'有了记录，我不想再手工画一遍甘特图', gallery:7 },
      { eyebrow:'03 / 让记录形成进度', title:'那张甘特图，<br>我<span>不想再手画。</span>',
        story:['给 teammate 或上司说明进度，给自己留一份回顾，我都需要甘特图。但我不想把已经做过的事情，再搬进另一张表里画一遍。','既然计划、执行与完成状态都记下来了，就让它们直接形成甘特图；再用时间统计，帮助我判断投入分布和明天的安排。'],
        features:[['看计划，也看实际','任务颜色、多段执行、子任务与完成时点，可在日、周、月跨度查看。'],['导出与分享','按范围导出 Excel 或 HTML，让同事、上司和自己都能查看进度。'],['分析时间利用率','比较本人工作与 AI 投入，按作息设置可用时间；可查看滚动周趋势，重叠时间按并集统计。']],
        result:'记录一次，得到进度图和时间回顾，把汇报的精力用在成果与下一步上。', next:'每天都在推进，大 Project 的全貌呢？', gallery:2 },
      { eyebrow:'04 / 从大项目走到每一天', title:'完成了很多任务，<br><span>项目全貌</span>在哪里？',
        story:['任务记得越来越清楚，我却发现自己仍然不够了解大项目的结构和进度。今天做的这一件事，究竟在为哪个目标服务？','于是有了 Project → 目标 → Task 的树。先设计项目框架，再把阶段目标拆成每日可做的任务；项目有变化，也能继续调整结构。'],
        features:[['多层目标与任务','Project、阶段目标、下级目标、Task、子任务逐层组织。'],['列表与图形两种视角','查看层级，也能拖动节点、自动排列、调整关系和外观。'],['追踪大项目进展','把每日执行放回对应目标，查看哪些已完成、哪些仍需要投入。']],
        result:'每天开始时，知道眼前的工作属于哪里；回顾时，看得到整个项目往前走了多少。', next:'功能变多以后，我想直接用对话来安排', gallery:1 },
      { eyebrow:'05 / 让对话管理日程', title:'入口多了，<br>就让 AI <span>帮我操作。</span>',
        story:['项目、目标、日程、计时、会话、统计……每项功能都有来处，放在一起却越来越复杂。我已经习惯与 AI 对话，也希望直接说出安排。','因此我加入了内置 AI 聊天助手，以及供外部 Agent 使用的 MCP。一个留在手边的小窗里，一个接入我原本的 AI 工作流程。'],
        features:[['悬浮窗里的聊天管理','说出安排，让助手协助新建或调整任务、补录工作时间、整理项目。'],['外部 Agent 接入 MCP','常用的 AI Agent 可以通过 MewMent 的受控工具管理日程。'],['分别选择模型','聊天与本地会话摘要可按各自用途，选择本机 Agent 或自定义模型 API。']],
        result:'这里的 AI 接收新指令、帮助操作日程；前一章的摘要功能，则整理已经发生的本地 AI 协作。', next:'最后，也给认真工作的日常留一只猫', gallery:0 },
      { eyebrow:'06 / 软件里的一点私心', title:'功能之外，<br>我还想<span>留一只猫。</span>',
        story:['我喜欢猫的灵巧、好奇和一点神秘感。既然这是一个每天都会打开的工具，我也希望它有自己喜欢的温度。','Mew 与 Moment 组成了 MewMent。黑猫眼睛里的时钟记着投入，小墨则住进了悬浮窗和对话里：会开心、会伸懒腰，也会陪着我安静一会儿。'],
        features:[['黑猫时钟 Logo','用猫咪与时间构成软件自己的识别。'],['聊天中的猫咪伙伴','摸头、逗猫、伸展与休息，配合真实角色动作。'],['不同的猫咪形象','11 种伙伴，让长期使用的工具有一点属于自己的亲近感。']],
        result:'我想把时间用得更明白，也希望陪我工作的工具，值得每天再见一次。', next:'回到 MewMent 的起点', gallery:3 }
    ]
  },
  en: {
    readingTabs:['The story','Features & use','Try it'], next:'Next', outcome:'What I wanted to solve', demoHint:'Try the product on the right. All examples use fictional data.',
    productDefinition:'MewMent · A Windows planner for personal work and local AI collaboration',
    homePreview:'Open the complete MewMent product demo', homePreviewCaption:'MewMent: calendar, tasks and work records in one window',
    homeBridge:'It started as a timer. These features grew from there.', featuresLabel:'Inside this chapter', sourceNote:'Creator’s journal · Built around real work',
    aiDate:'On which day', aiDuration:'AI work that day', aiSource:'Source retained', aiEffort:'55 minutes',
    aiRecordLabel:'Example · 24 September 2026', aiActivity:'3 activity spans · 20 + 25 + 10 min',
    aiDestinations:['AI work in the daily agenda','Included in the Gantt view','Included in time statistics'],
    aiFlow:['Local sessions & original locations','Content summaries + time records','Agenda, Gantt & statistics'],
    aiScope:'Multiple sources can be connected together. Selecting one here only changes the example.',
    insightModes:['Gantt & export','Time utilization'], insightGanttCaption:'Plans, actual work and completion points come from your existing records.', insightStatsCaption:'Review days, weeks and months, including personal work and AI collaboration.',
    exportNote:'Export Excel or HTML for teammates, a manager, or your future review.', exportButton:'See the export options',
    assistantModes:['Floating chat','External agents / MCP','Your model'], assistantCaption:'The small window shares its conversation with the full assistant.',
    mcpTitle:'Let your usual agent manage the schedule, too',mcpInput:'“Turn next week’s Starfield work into tasks.”',mcpSteps:['An external AI agent','MewMent MCP','Tasks / projects / time records'],mcpActions:['Find and create tasks','Adjust plans and projects','Record or backfill work'],mcpNote:'Actions go through the app’s controlled tools and its authorization and confirmation flow.',modelCaption:'Choose an Agent or custom API separately for session summaries and chat-based management.',
    chapters:[
      {eyebrow:'CREATOR’S JOURNAL / THE BEGINNING',title:'I wanted to know<br>where my <span>day went.</span>',story:['I care about making good use of time, and AI has become a deep part of my work. I switch between conversations and hands-on tasks, until the day feels scattered.','MewMent began as a timer. It grew into a way to put my own work and local AI collaboration back into the same agenda.'],features:[['Record work','Tasks, subtasks, multiple work sessions and backfilling.'],['Understand the time','Local AI sessions, Gantt views and time utilization.'],['Move a project forward','A project-goal-task tree and chat-based planning.']],result:'After a busy day, I want to know what I did, how long it took, and where the project stands.',next:'First, record the work I actually do',gallery:4},
      {eyebrow:'01 / IT STARTED WITH A TIMER',title:'First, record<br>the work I <span>actually do.</span>',story:['At first I only wanted a convenient timer. Start when work begins, pause when interrupted, and continue later. Each piece of effort should stay with the same task.','Once those records existed, plans, subtasks and a calendar could connect to them. If I forgot the timer, I could fill the gap afterward.'],features:[['Tasks and subtasks','Keep names, plans, colors and completion notes together.'],['Multiple sessions and backfilling','Start and pause a task repeatedly while retaining each stretch of actual work.'],['Agenda and floating timer','Plan dates in the calendar, compare plans with execution, and keep a small timer or countdown nearby.']],result:'Turn “I was busy today” into work and time I can actually review.',next:'But time spent collaborating with AI was still missing',gallery:4},
      {eyebrow:'02 / COUNTING AI COLLABORATION',title:'Work done with AI<br>needs a <span>time record, too.</span>',story:['I move between local agents and workspaces. Tracking hands-on tasks alone cannot tell me which day I worked with AI, what we did, or how long it took. The sessions are scattered, too.','So I added local-session collection and automatic summaries: keep the source, content, date and time information together, and bring that work into the agenda, Gantt view and statistics.'],features:[['Gather local sessions','Organize sources such as Codex, Claude Code, OpenCode, OpenClaw, Hermes and Pi, retaining tool and workspace context.'],['Content and time have their own evidence','Summaries describe the collaboration. Dates, activity spans and duration come from the records each source can provide.'],['One record of the working day','Review personal work alongside AI collaboration, understand the effort and progress, and find the original session.']],result:'Know which day I spent time talking or working with AI, and how much. That effort should be part of the schedule.',next:'With the records in place, why draw the Gantt chart again?',gallery:7},
      {eyebrow:'03 / FROM RECORDS TO PROGRESS',title:'The Gantt chart<br>I didn’t want to <span>draw.</span>',story:['I need a Gantt chart to explain progress to a teammate or manager, and to look back myself. I do not want to copy completed work into another sheet and draw it all again.','Plans, execution and completion are already recorded. Let them form the chart, then use time statistics to decide where tomorrow’s effort should go.'],features:[['Plans and actual work','See task colors, multiple sessions, subtasks and completion points across days, weeks and months.'],['Export and share','Export a date range to Excel or HTML for the people who need to see the progress.'],['Understand time utilization','Review personal and AI effort against available working time, including rolling-week trends and overlapping time counted as a union.']],result:'Record work once; get a progress view and a time review from it.',next:'Daily progress is clearer. What about the whole project?',gallery:2},
      {eyebrow:'04 / THE PROJECT BEHIND THE DAY',title:'Lots of tasks done.<br>Where is the <span>big picture?</span>',story:['My task records were improving, but a large project could still feel shapeless. Which goal did today’s work actually belong to?','That led to a Project → Goal → Task tree. Design the structure, break goals into daily work, and adjust the relationships as the project changes.'],features:[['A hierarchy that keeps going','Projects, stage goals, lower-level goals, tasks and subtasks.'],['Lists and a movable graph','Inspect the hierarchy, drag nodes, arrange them, and adjust relationships and appearance.'],['Track the whole project','Place daily execution back under its goals and see what is done and what still needs time.']],result:'Know where today’s task belongs, and how far the larger project has moved.',next:'As the controls multiplied, I wanted to just say the plan',gallery:1},
      {eyebrow:'05 / MANAGING THROUGH CONVERSATION',title:'More features.<br>Let AI <span>help me use them.</span>',story:['Projects, goals, schedules, timers, sessions, statistics… Each feature had a reason, but together they meant more controls. I already worked through conversation with AI.','So I added an in-app assistant and MCP tools for external agents: one in a small window nearby, the other inside my existing AI workflow.'],features:[['Chat in the floating window','Ask for help creating or adjusting tasks, backfilling time and organizing projects.'],['External agents through MCP','Let a compatible agent manage the schedule through MewMent’s controlled tools.'],['Choose models by purpose','Use a local Agent or custom model API independently for chat and local-session summaries.']],result:'This AI takes new instructions to manage the schedule. Session summaries organize local AI collaboration that has already happened.',next:'And finally, a cat to keep me company',gallery:0},
      {eyebrow:'06 / A PERSONAL TOUCH',title:'Along with the features,<br>I wanted <span>a cat.</span>',story:['I love a cat’s curiosity, agility and little air of mystery. A tool I open every day should have some of that warmth, too.','Mew meets Moment in MewMent. A clock lives in the black cat’s eye; Ink lives in the floating window and chat, ready to play, stretch, or quietly keep me company.'],features:[['A black-cat clock','Cats and time give the app its own recognizable mark.'],['A companion in the conversation','Pet, play, stretch and rest with the product’s original character animations.'],['Different feline personalities','11 companions make a daily tool feel a little more personal.']],result:'I want to understand my time—and enjoy the tool that stays beside me while I work.',next:'Back to the beginning of MewMent',gallery:3}
    ]
  }
};
