(() => {
  'use strict';
  const root = document.getElementById('app');
  const defaultPositions = [{x:50,y:13},{x:18,y:44},{x:50,y:44},{x:82,y:44},{x:50,y:78}];
  const state = { lang: new URLSearchParams(location.search).get('lang') || safeRead('mewment-language') || 'zh', scene: 0, reading:'story', insight:0, assistantMode:0, paused: matchMedia('(prefers-reduced-motion: reduce)').matches, running: false, elapsed: 0, startAt: 0, pets: 0, day:5, dayMode:0, tasks:[false,false,false], gantt:0, agent:0, expanded:false, phase:0, projectDone:[false,false,false], positions:defaultPositions.map(p=>({...p})), cat:0, modal:null, family:false };
  const mediaRoot = 'Resource/media/';
  const galleryFiles = [ ['17-floating-chat-switch.gif','11-mini-chat.png'], ['06c-project-free-edit.gif','06-project-graph.png'], ['08-gantt-expand.gif','08-gantt-subtasks.png'], ['18-cat-actions-compact.gif','18-cat-actions-compact-poster.png'], ['01-main-panorama.png','01-main-panorama.png'], ['16-floating-timer.png','16-floating-timer.png'], ['10-statistics.png','10-statistics.png'], ['03-ai-multi-agent.png','03-ai-multi-agent.png'], ['09-gantt-export.png','09-gantt-export.png'] ];
  const liveScenes = ['floating','project','gantt','cats','overview',null,null,'ai',null];
  const agents = ['Codex','Claude Code','OpenCode','OpenClaw','Hermes','Pi'];
  let dialogReturnFocus = null;
  if (!['zh','en'].includes(state.lang)) state.lang = 'zh';
  function safeRead(key) { try { return localStorage.getItem(key); } catch { return null; } }
  function safeWrite(key, value) { try { localStorage.setItem(key, value); } catch { /* File and privacy modes remain usable. */ } }
  const t = () => window.MewContent[state.lang];
  const n = () => window.MewNarrative[state.lang];
  const icon = (name) => {
    const paths = { arrow:'<path d="M4 12h15m-6-6 6 6-6 6"/>', play:'<path d="m8 5 11 7-11 7Z"/>', pause:'<path d="M8 5v14M16 5v14"/>', heart:'<path d="M20 5c-3-3-7-1-8 1-1-2-5-4-8-1-5 5 3 11 8 15 5-4 13-10 8-15Z"/>', home:'<path d="m3 10 9-7 9 7M6 9v11h12V9M10 20v-7h4v7"/>', day:'<rect x="4" y="5" width="16" height="16" rx="3"/><path d="M8 3v4M16 3v4M4 11h16M8 15h3"/>', memory:'<path d="M21 11a8 8 0 0 1-8 8H6l-4 3V11a9 9 0 0 1 19 0Z"/><path d="M7 10h8M7 14h5"/>', project:'<rect x="8" y="2" width="8" height="5" rx="1"/><path d="M12 7v5M5 12h14M5 12v4M19 12v4"/><rect x="2" y="16" width="6" height="5" rx="1"/><rect x="16" y="16" width="6" height="5" rx="1"/>', cat:'<path d="M5 10 4 3l6 4h4l6-4-1 7c5 10-19 10-14 0Z"/><path d="M8 12h1M15 12h1M11 15h2"/>', close:'<path d="m6 6 12 12M18 6 6 18"/>', check:'<path d="m5 12 5 5L20 7"/>', expand:'<path d="M9 3H3v6M15 3h6v6M3 15v6h6M21 15v6h-6"/>', reset:'<path d="M4 10a8 8 0 1 1 1 8M4 4v6h6"/>' };
    return `<svg viewBox="0 0 24 24" class="icon" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">${paths[name] || paths.heart}</svg>`;
  };
  // Original MewMent brand geometry, reused from the supplied animated mark.
  function mark(id) { return `<svg viewBox="0 0 1024 1024" aria-hidden="true" class="hero-mark"><defs><linearGradient id="${id}-cat" x1="256" y1="180" x2="790" y2="900" gradientUnits="userSpaceOnUse"><stop stop-color="#1d1e23"/><stop offset="1" stop-color="#090a0d"/></linearGradient><linearGradient id="${id}-gold" x1="282" y1="480" x2="760" y2="744" gradientUnits="userSpaceOnUse"><stop stop-color="#ffc83d"/><stop offset="1" stop-color="#f2a900"/></linearGradient></defs><path d="M170 452C160 332 162 198 194 146C220 104 310 177 426 276C454 268 483 264 512 264C541 264 570 268 598 276C714 177 804 104 830 146C862 198 864 332 854 452C900 508 922 584 914 664C899 835 734 918 512 918C290 918 125 835 110 664C102 584 124 508 170 452Z" fill="url(#${id}-cat)" stroke="#f4f0e8" stroke-width="14" stroke-linejoin="round"/><circle cx="385" cy="604" r="148" fill="url(#${id}-gold)"/><circle cx="716" cy="604" r="70" fill="url(#${id}-gold)"/><path d="M385 604V492M385 604L293 661" fill="none" stroke="#111216" stroke-width="40" stroke-linecap="round"/><circle cx="385" cy="604" r="34" fill="#111216"/><path class="clock-hand" d="M385 604L486 686" fill="none" stroke="#ef3f4f" stroke-width="18" stroke-linecap="round"/><circle cx="385" cy="604" r="18" fill="#ef3f4f"/></svg>`; }
  function timerText() { const total = Math.floor((state.elapsed + (state.running ? Date.now()-state.startAt : 0))/1000); return [Math.floor(total/60), total%60].map(n=>String(n).padStart(2,'0')).join(':'); }
  function render(focusSelector) {
    const c=t(); document.documentElement.lang=state.lang==='zh'?'zh-CN':'en'; document.title=c.title; document.querySelector('meta[name="description"]').content=c.description; document.documentElement.dataset.motion=state.paused?'paused':'running';
    root.innerHTML = `<div class="site-shell"><header class="site-header"><button class="wordmark" data-action="home" aria-label="MewMent"><img src="Resource/media/mark.svg" alt="" width="46" height="46"><span>MewMent<span class="wordmark-dot">.</span></span></button><div class="header-right"><button class="story-link" data-action="story">${c.story}</button><div class="header-divider"></div><button class="language-switch" data-action="language" aria-label="${c.lang}"><span class="${state.lang==='zh'?'active':''}">中</span><span class="switch-slash">/</span><span class="${state.lang==='en'?'active':''}">EN</span></button><button class="motion-switch" data-action="motion" aria-label="${state.paused?c.resumeMotion:c.motion}" title="${state.paused?c.resumeMotion:c.motion}">${icon(state.paused?'play':'pause')}</button></div></header><main id="main" tabindex="-1" class="scene scene-${state.scene}" data-expanded="${state.expanded}" data-reading="${state.reading}">${renderScene()}</main><footer class="site-footer"><div class="scene-index"><span class="current-index">0${state.scene+1}</span><span class="index-line"></span><span>0${c.nav.length}</span></div><nav class="scene-nav" aria-label="${c.navLabel}">${c.nav.map((label,i)=>`<button data-scene="${i}" aria-label="${label}" class="nav-item ${state.scene===i?'selected':''}" aria-current="${state.scene===i?'page':'false'}">${icon(['home','day','memory','expand','project','memory','cat'][i])}<span class="nav-long">${label}</span><span class="nav-short" aria-hidden="true">${c.navShort[i]}</span></button>`).join('')}</nav><div class="footer-whisper">${c.footer}<span>${c.keyboard}</span></div></footer></div><div id="modal-root"></div>`;
    drawConnections();
    window.MewMotion.sync();
    if(state.modal) mountDialog();
    if(focusSelector&&!state.modal) document.querySelector(focusSelector)?.focus({preventScroll:true});
    document.querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{img.closest('figure,.cat-window')?.classList.add('media-error'); document.getElementById('announcer').textContent=c.imageError;},{once:true}));
  }
  function renderScene(){ return [home,day,aiRecords,insights,projects,assistantDemo,companion][state.scene](); }
  function home() {
    const c=t(),v=n();
    return `<section class="intro home-intro"><div class="eyebrow"><span></span>${c.homeEyebrow}</div><h1>${c.homeTitle}</h1><p class="product-definition">${v.productDefinition}</p><p class="intro-body">${c.homeBody}</p><div class="intro-actions"><button class="primary-button" data-scene="1">${c.explore}${icon('arrow')}</button><button class="text-button" data-gallery="4">${icon('play')}${c.demo}</button></div><div class="home-feature-map" aria-label="${c.navLabel}"><p>${v.homeBridge}</p>${c.nav.slice(1).map((label,i)=>`<button data-scene="${i+1}"><span>0${i+1}</span>${label}${icon('arrow')}</button>`).join('')}</div></section><section class="cat-universe product-universe" aria-label="${v.homePreviewCaption}"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><span class="orbit-dot dot-one"></span><span class="orbit-dot dot-two"></span><div class="cat-shadow"></div><button class="home-product-preview" data-gallery="4" aria-label="${v.homePreview}"><span class="preview-chrome"><i></i><i></i><i></i><strong>MewMent / Windows</strong></span><span class="home-product-view" inert aria-hidden="true">${productSurface('overview',4)}</span><span class="preview-caption">${v.homePreviewCaption}${icon('expand')}</span></button><button class="hero-cat" data-action="pet" aria-label="${c.catPet}">${mark('hero')}<span class="cat-touch-hint">${c.catHint} ${icon('heart')}</span></button><div class="hello-bubble" id="hello">${c.catHello}</div><div class="float-card timer-card"><div class="card-eyebrow"><span class="tiny-red-dot ${state.running?'running':''}"></span>${c.timerLabel}</div><div class="timer-value" data-timer>${timerText()}</div><div class="timer-bottom"><span>${c.timerTask}</span><button class="timer-toggle" data-action="timer" aria-label="${state.running?c.timerPause:c.timerStart}">${icon(state.running?'pause':'play')}</button></div></div><button class="float-card memory-card" data-scene="2"><span class="memory-symbol">${icon('memory')}</span><span><strong>${c.memoryLabel}</strong><small>${c.memoryText}</small></span>${icon('arrow')}</button></section>`;
  }
  function productSurface(scene,index){return !state.paused?window.MewMotion.productFrame({scene,lang:state.lang,title:t().galleryNames[index],poster:mediaPath(index,true)}):`<img class="product-still" src="${mediaPath(index,true)}" alt="${t().galleryNames[index]}">`;}
  function chapterCopy(){
    const v=n(),chapter=v.chapters[state.scene];
    if(state.reading==='features')return `<dl class="chapter-features">${chapter.features.map(([title,body],i)=>`<div><dt><span>0${i+1}</span>${title}</dt><dd>${body}</dd></div>`).join('')}</dl>`;
    if(state.reading==='demo')return `<div class="chapter-demo-intro"><span class="chapter-demo-icon">${icon('play')}</span><p>${chapter.result}</p><small>${v.demoHint}</small></div>`;
    return `<div class="chapter-story">${chapter.story.map(p=>`<p>${p}</p>`).join('')}</div><p class="chapter-outcome"><span>${v.outcome}</span>${chapter.result}</p>`;
  }
  function updateReading(){
    document.getElementById('main').dataset.reading=state.reading;
    document.querySelectorAll('[data-reading-choice]').forEach(button=>{const active=button.dataset.readingChoice===state.reading;button.classList.toggle('active',active);button.setAttribute('aria-selected',String(active));button.tabIndex=active?0:-1;});
    const panel=document.getElementById('chapter-copy');panel.innerHTML=chapterCopy();panel.setAttribute('aria-labelledby','reading-'+state.reading);
    window.MewMotion.holdBackground(matchMedia('(max-width: 760px)').matches&&state.reading!=='demo');
  }
  function sectionIntro() {
    const c=t(),v=n(),chapter=v.chapters[state.scene];
    return `<section class="intro feature-intro"><div class="eyebrow"><span></span>${chapter.eyebrow}</div><h1>${chapter.title}</h1><div class="reading-tabs" role="tablist" aria-label="${v.featuresLabel}">${['story','features','demo'].map((key,i)=>`<button data-reading-choice="${key}" role="tab" id="reading-${key}" aria-controls="chapter-copy" aria-selected="${state.reading===key}" tabindex="${state.reading===key?0:-1}" class="${state.reading===key?'active':''}">${v.readingTabs[i]}</button>`).join('')}</div><div id="chapter-copy" class="chapter-copy" role="tabpanel" aria-labelledby="reading-${state.reading}">${chapterCopy()}</div><div class="feature-links"><button class="text-button actual-button" data-gallery="${chapter.gallery}">${icon('play')}${c.actual}${icon('arrow')}</button></div><button class="chapter-next" data-scene="${(state.scene+1)%7}"><span>${v.next} /</span>${chapter.next}${icon('arrow')}</button></section>`;
  }
  function panelTop(title,extra='') { return `<div class="panel-top"><span class="panel-brand"><img src="${mediaRoot}mark.svg" width="25" height="25" alt="">${title}</span>${extra}</div>`; }
  function day() {
    const c=t(); return sectionIntro()+`<section class="product-stage day-stage" aria-label="${c.nav[1]}"><div class="paper-panel">${panelTop('MewMent',`<button class="icon-button" data-action="reset-day" aria-label="${c.reset}" title="${c.reset}">${icon('reset')}</button>`)}<div class="day-panel-heading"><span>SEPTEMBER, 2026</span><strong>${c.dayNames[state.day]}</strong></div><div class="week-strip" aria-label="${state.lang==='zh'?'选择示例日期':'Select a demo date'}">${c.week.map((d,i)=>`<button data-day="${i}" aria-label="${state.lang==='zh'?'9 月 '+(21+i)+' 日':'September '+(21+i)}" aria-pressed="${state.day===i}" class="${state.day===i?'chosen':''}"><span>${d}</span><strong>${21+i}</strong><i></i></button>`).join('')}</div><div class="mode-tabs" role="tablist" aria-label="${c.nav[1]}">${c.dayModes.map((label,i)=>`<button data-mode="${i}" id="mode-${i}" role="tab" aria-controls="day-panel" aria-selected="${state.dayMode===i}" tabindex="${state.dayMode===i?'0':'-1'}" class="${state.dayMode===i?'active':''}">${label}</button>`).join('')}</div><div class="day-mode-content" id="day-panel" role="tabpanel" aria-labelledby="mode-${state.dayMode}">${[taskDemo,ganttDemo,statsDemo][state.dayMode]()}</div><div class="demo-caption"><span>${c.demoTag}</span><span>${icon('heart')}</span></div></div><div class="stage-footnote">${c.historySegments}</div></section>`;
  }
  function taskDemo() { const c=t(); return `<div class="task-stack">${c.dayTasks.map((title,i)=>`<div class="demo-task task-color-${i} ${state.tasks[i]?'done':''}"><button class="task-check ${state.tasks[i]?'checked':''}" data-task="${i}" aria-label="${state.tasks[i]?c.restoreTask:c.completeTask} · ${title}" aria-pressed="${state.tasks[i]}">${state.tasks[i]?icon('check'):''}</button><div class="task-description"><strong>${title}</strong><span>${state.tasks[i]?c.complete:i===0&&state.running?c.inProgress:c.waiting}</span></div>${i===0&&!state.tasks[i]?`<div class="task-timer"><span data-timer>${timerText()}</span><button class="timer-toggle" data-action="timer" aria-label="${state.running?c.timerPause:state.elapsed?c.timerResume:c.timerStart}">${icon(state.running?'pause':'play')}</button></div>`:`<span class="task-decoration">${state.tasks[i]?'✓':i===1?'15:00':'20:30'}</span>`}</div>`).join('')}</div><div class="task-summary"><span>${state.tasks.filter(Boolean).length} / 3 ${c.taskCount}</span><div class="task-summary-track"><i style="width:${state.tasks.filter(Boolean).length/3*100}%"></i></div></div>`; }
  function ganttDemo(){ const c=t(); return `<div class="gantt-demo"><div class="chart-heading">${c.ganttTitle}<span><i class="planned-key"></i>${c.planned}<i class="recorded-key"></i>${c.recorded}</span></div><div class="gantt-scale"><span>09:00</span><span>12:00</span><span>15:00</span><span>18:00</span></div>${c.dayTasks.map((title,i)=>`<button class="gantt-row ${state.gantt===i?'selected':''}" data-gantt="${i}" aria-expanded="${state.gantt===i}"><span>${title}</span><div class="gantt-track color-${i}"><i class="gantt-plan" style="left:${i*19}%;width:${40-i*7}%"></i><i class="gantt-actual" style="left:${i*19+1}%;width:${17-i*2}%"></i><i class="gantt-actual second" style="left:${i*19+22}%;width:9%"></i></div></button>`).join('')}<div class="execution-detail">${icon('check')}<span>${c.segments[state.gantt]}</span></div><p class="micro-note">${c.ganttHint}</p></div>`; }
  function statsDemo(){ const c=t(), values=[45,68,49,84,62,35,19]; return `<div class="stats-demo"><div class="chart-heading">${c.statsTitle}</div><div class="stats-total"><strong>18.5</strong><span>${c.statsUnit}<small>${c.statsTotal}</small></span></div><div class="bar-chart" aria-label="${c.statsTitle}">${values.map((v,i)=>`<button data-day="${i}" class="bar-column ${state.day===i?'chosen':''}" aria-label="${c.dayNames[i]} · ${(v/25).toFixed(1)} ${c.statsUnit}"><span class="bar-shape" style="--bar-height:${v}%"><i></i><i></i><i></i></span><span>${c.week[i]}</span></button>`).join('')}</div><div class="chart-legend">${c.statsCategories.map((l,i)=>`<span><i class="legend-${i}"></i>${l}</span>`).join('')}</div><p class="micro-note stats-note">${c.statsNote}</p></div>`; }
  function aiRecords(){
    const c=t(),v=n();
    return sectionIntro()+`<section class="product-stage ai-stage" aria-label="${c.nav[2]}"><div class="source-label">${c.aiLocal}</div><div class="agent-sources" role="group" aria-label="${c.aiLocal}">${agents.map((name,i)=>`<button data-agent="${i}" aria-pressed="${state.agent===i}" class="agent-source ${state.agent===i?'active':''}"><span class="agent-glyph" aria-hidden="true">${['✳','✦','◈','⌘','H','π'][i]}</span>${name}</button>`).join('')}</div><p class="source-scope">${v.aiScope}</p><div class="record-flow" aria-hidden="true">${v.aiFlow.map((label,i)=>`<span>${label}</span>${i<2?icon('arrow'):''}`).join('')}</div><div class="paper-panel archive-panel">${panelTop(c.aiArchive,`<span class="archive-state">${icon('check')}${c.aiStatus}</span>`)}<div class="memory-record"><div class="memory-meta"><span>${agents[state.agent]} / ${state.agent%2?'WSL':'Windows'}</span><span>${v.aiRecordLabel}</span></div><h2>${c.aiSessionTitle}</h2><div class="ai-time-evidence"><div><span>${v.aiDate}</span><strong>09 / 24</strong></div><div><span>${v.aiDuration}</span><strong>${v.aiEffort}</strong></div><div><span>${v.aiSource}</span><strong>Starfield / research</strong></div></div><div class="activity-spans" aria-label="${v.aiActivity}"><i style="--span:20">20m</i><i style="--span:25">25m</i><i style="--span:10">10m</i><span>${v.aiActivity}</span></div><button class="memory-toggle" data-action="expand-memory" aria-expanded="${state.expanded}" aria-controls="memory-details">${state.expanded?c.aiCollapse:c.aiOpen}<span aria-hidden="true">${state.expanded?'−':'+'}</span></button><div id="memory-details" class="memory-details" ${state.expanded?'':'hidden'}><h3>${c.aiSummaryTitle}</h3><p>${c.aiSummary}</p></div><p class="micro-note evidence-note">${c.aiEvidence}</p></div><div class="record-destinations">${v.aiDestinations.map(label=>`<span>${icon('check')}${label}</span>`).join('')}</div></div><p class="provider-note">${c.aiPrivacy}</p></section>`;
  }
  function insights(){
    const c=t(),v=n();
    return sectionIntro()+`<section class="product-stage insight-stage"><div class="paper-panel">${panelTop('MewMent · '+c.nav[3])}<div class="stage-switch" role="group" aria-label="${c.nav[3]}">${v.insightModes.map((label,i)=>`<button data-insight="${i}" aria-pressed="${state.insight===i}" class="${state.insight===i?'active':''}">${label}</button>`).join('')}</div><div class="embedded-product insight-product">${state.insight===0?productSurface('gantt',2):`<button class="screenshot-button" data-gallery="6" aria-label="${c.fullSize}"><img class="product-still" src="${mediaPath(6,true)}" alt="${c.galleryNames[6]}"></button>`}</div><p class="native-caption">${state.insight===0?v.insightGanttCaption:v.insightStatsCaption}</p><div class="export-callout"><span>${v.exportNote}</span><button class="text-button" data-gallery="8">${v.exportButton}${icon('arrow')}</button></div></div></section>`;
  }
  function assistantDemo(){
    const c=t(),v=n();
    let surface=productSurface('floating',0);
    if(state.assistantMode===1)surface=`<div class="mcp-demo"><span class="mcp-prompt">${v.mcpInput}</span><div class="mcp-route">${v.mcpSteps.map((label,i)=>`<div><span>0${i+1}</span><strong>${label}</strong></div>${i<2?icon('arrow'):''}`).join('')}</div><div class="mcp-actions">${v.mcpActions.map(label=>`<span>${icon('check')}${label}</span>`).join('')}</div><p>${v.mcpNote}</p></div>`;
    if(state.assistantMode===2)surface=`<a class="model-screenshot" href="${mediaRoot+(state.lang==='en'?'en/':'')}22-model-api.png" target="_blank" rel="noopener" aria-label="${c.fullSize}"><img class="product-still" src="${mediaRoot+(state.lang==='en'?'en/':'')}22-model-api.png" alt="${v.modelCaption}"></a>`;
    return sectionIntro()+`<section class="product-stage assistant-stage"><div class="paper-panel">${panelTop('MewMent · '+c.nav[5])}<div class="stage-switch" role="group" aria-label="${c.nav[5]}">${v.assistantModes.map((label,i)=>`<button data-assistant="${i}" aria-pressed="${state.assistantMode===i}" class="${state.assistantMode===i?'active':''}">${label}</button>`).join('')}</div><div class="embedded-product assistant-product assistant-mode-${state.assistantMode}">${surface}</div><p class="native-caption">${[v.assistantCaption,v.mcpTitle,v.modelCaption][state.assistantMode]}</p></div></section>`;
  }
  function projects(){const c=t();return sectionIntro()+`<section class="product-stage project-stage"><div class="paper-panel">${panelTop('MewMent · Project',`<button class="arrange-button" data-action="arrange">${icon('reset')}${c.projectArrange}</button>`)}<div class="project-canvas" aria-label="${c.projectRoot}"><svg class="project-lines" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path data-edge="0-1"/><path data-edge="0-2"/><path data-edge="0-3"/><path data-edge="${state.phase+1}-4" class="selected-edge"/></svg>${[c.projectRoot,...c.projectPhases,c.projectLeaf].map((label,i)=>`<button data-node="${i}" style="left:${state.positions[i].x}%;top:${state.positions[i].y}%" class="graph-node node-${i} ${i===state.phase+1?'active':''}" aria-label="${label}" ${i>0&&i<4?`aria-pressed="${state.phase===i-1}"`:''}>${i===0?`<img src="${mediaRoot}mark.svg" width="22" height="22" alt="">`:i===4?icon('day'):`<span class="phase-number">0${i}</span>`}<span>${label}</span>${i>0&&i<4&&state.projectDone[i-1]?icon('check'):''}</button>`).join('')}</div><div class="project-detail"><div><span class="card-eyebrow">${c.projectSelected}</span><h3>${c.projectTasks[state.phase][0]}</h3><p>${c.projectTasks[state.phase][1]}</p></div><button class="step-done ${state.projectDone[state.phase]?'completed':''}" data-action="complete-step" aria-pressed="${state.projectDone[state.phase]}" aria-label="${state.projectDone[state.phase]?c.projectUndo:c.projectDone}">${icon(state.projectDone[state.phase]?'check':'arrow')}</button></div><div class="project-progress"><span>${c.projectProgress}</span><span>${state.projectDone.filter(Boolean).length} / 3</span><div><i style="width:${state.projectDone.filter(Boolean).length/3*100}%"></i></div></div></div><p class="stage-footnote">${c.projectHint}</p></section>`;}
  function companion(){const c=t(),crop=[3,4,2,7][state.cat];return sectionIntro()+`<section class="product-stage companion-stage"><div class="companion-bubble" aria-live="polite">${c.catReplies[state.cat]}</div><div class="companion-halo"></div><button class="cat-window" style="--poster-x:${-(crop%4)*100}%;--poster-y:${-Math.floor(crop/4)*100}%" data-action="next-cat" aria-label="${c.catPet}">${!state.paused?window.MewMotion.productFrame({scene:'cats',lang:state.lang,title:c.catActions[state.cat],poster:mediaRoot+(state.lang==='en'?'en/':'')+'18-cat-actions-compact-poster.png',action:state.cat}):`<span class="cat-crop"><img src="${mediaRoot+(state.lang==='en'?'en/':'')+(state.paused?'18-cat-actions-compact-poster.png':'18-cat-actions-compact.gif')}" alt="${c.catActions[state.cat]}" style="left:${-(crop%4)*100}%;top:${-Math.floor(crop/4)*100}%"></span>`}</button><div class="cat-actions" role="group" aria-label="${c.catPet}">${c.catActions.map((label,i)=>`<button data-cat="${i}" aria-pressed="${state.cat===i}" class="${state.cat===i?'active':''}">${icon(['heart','cat','expand','pause'][i])}<span>${label}</span></button>`).join('')}</div><div class="companion-note"><span>${c.catActivity}</span><button class="text-button" data-action="family">${c.catFamily} ${icon('arrow')}</button></div><button class="mobile-story text-button" data-action="story">${c.story}</button></section>`;}
  function updateCompanion(){
    const c=t(),crop=[3,4,2,7][state.cat],button=document.querySelector('.cat-window');
    document.querySelector('.companion-bubble').textContent=c.catReplies[state.cat];
    document.querySelectorAll('[data-cat]').forEach(el=>{const active=Number(el.dataset.cat)===state.cat;el.classList.toggle('active',active);el.setAttribute('aria-pressed',String(active));});
    button.style.setProperty('--poster-x',(-(crop%4)*100)+'%');button.style.setProperty('--poster-y',(-Math.floor(crop/4)*100)+'%');
    const poster=button.querySelector('.cat-crop img');if(poster){poster.style.left=(-(crop%4)*100)+'%';poster.style.top=(-Math.floor(crop/4)*100)+'%';poster.alt=c.catActions[state.cat];}
    window.MewMotion.changeCat(state.cat,c.catActions[state.cat]);
  }
  function drawConnections(){if(state.scene!==4)return;document.querySelectorAll('[data-edge]').forEach(path=>{const [from,to]=path.dataset.edge.split('-').map(Number),a=state.positions[from],b=state.positions[to],mid=(a.y+b.y)/2;path.setAttribute('d',`M${a.x} ${a.y} C${a.x} ${mid},${b.x} ${mid},${b.x} ${b.y}`);});}
  function chooseScene(index) { state.scene=(index+7)%7; state.reading='story'; state.modal=null; render(`.scene-nav [data-scene="${state.scene}"]`); document.getElementById('announcer').textContent=t().nav[state.scene]; }
  function openDialog(kind,index=0){dialogReturnFocus=document.activeElement;state.modal={kind,index};mountDialog();}
  function closeDialog(){window.MewMotion.holdBackground(false);document.querySelector('dialog')?.close();document.getElementById('modal-root').innerHTML='';state.modal=null;if(dialogReturnFocus?.isConnected)dialogReturnFocus.focus({preventScroll:true});else document.querySelector('.scene-nav .selected')?.focus({preventScroll:true});}
  function mediaPath(index,still=false){const file=galleryFiles[index][state.paused||still?1:0];return mediaRoot+(state.lang==='en'&&(file.endsWith('.png')||index===3)?'en/':'')+file;}
  function liveGallery(index){return window.MewMotion.productFrame({scene:liveScenes[index],lang:state.lang,title:t().galleryNames[index],poster:mediaPath(index,true)});}
  function mountDialog(){window.MewMotion.holdBackground(true);const c=t(),m=state.modal,container=document.getElementById('modal-root');if(!m)return;const common=`<button class="dialog-close icon-button" data-action="close" aria-label="${c.close}">${icon('close')}</button>`;let body='';
    if(m.kind==='story'){body=`<div class="story-art">${mark('story')}<span>MEW + MOMENT</span></div><div class="story-copy"><div class="eyebrow">THE STORY OF MEWMENT</div><h2 id="dialog-title">${c.storyTitle}</h2><p>${c.storyP1}</p><p>${c.storyP2}</p><p>${c.storyP3}</p><blockquote>${c.storyBelief}</blockquote><button class="primary-button" data-scene="1">${c.storyCta}${icon('arrow')}</button></div>`;}
    else if(m.kind==='info'){const chapter=n().chapters[state.scene];body=`<div class="feature-info story-copy"><div class="eyebrow">${chapter.eyebrow}</div><h2 id="dialog-title">${chapter.title}</h2>${chapter.story.map(p=>`<p>${p}</p>`).join('')}<blockquote>${chapter.result}</blockquote><button class="primary-button" data-gallery="${chapter.gallery}">${c.actual}${icon('play')}</button></div>`;}
    else if(m.kind==='family'){body=`<div class="family-content"><div class="eyebrow">A LITTLE CAT LOVE</div><h2 id="dialog-title">${c.catFamily}</h2><p>${c.catFamilyBody}</p><img src="${mediaRoot+(state.lang==='en'?'en/':'')}13-cartoon-cats.png" alt="${c.catFamilyBody}" width="1200" height="540"><button class="primary-button" data-action="close">${c.close}</button></div>`;}
    else{const idx=m.index;body=`<div class="gallery-header"><div><div class="eyebrow">THE MEWMENT THEATRE</div><h2 id="dialog-title">${c.galleryTitle}</h2><p>${c.gallerySubtitle}</p></div><div class="gallery-controls"><button class="icon-button replay-button" data-action="replay-demo" aria-label="${c.replayDemo}" title="${c.replayDemo}">${icon('reset')}</button><button class="language-switch" data-action="language" aria-label="${c.lang}">${state.lang==='zh'?'EN':'中文'}</button><button class="motion-switch" data-action="motion" aria-label="${state.paused?c.resumeMotion:c.motion}">${icon(state.paused?'play':'pause')}</button></div></div><div class="gallery-layout"><nav class="gallery-nav" aria-label="${c.galleryIndex}">${c.galleryNames.map((name,i)=>`<button data-gallery="${i}" aria-current="${idx===i?'true':'false'}" class="${idx===i?'active':''}"><span>0${i+1}</span>${name}${icon('arrow')}</button>`).join('')}</nav><figure class="gallery-figure"><div class="gallery-image-wrap">${!state.paused&&liveScenes[idx]?liveGallery(idx):`<img src="${mediaPath(idx,true)}" alt="${c.galleryNames[idx]}" class="${idx===4?'panorama':''}">`}</div><figcaption><div><span class="playback-tag">${icon(state.paused||!liveScenes[idx]?'pause':'play')}${state.paused||!liveScenes[idx]?c.galleryStill:c.galleryLoop}</span><p>${c.galleryCaptions[idx]}</p>${!state.paused&&liveScenes[idx]&&idx!==3?`<small>${c.liveHint}</small>`:''}</div><a href="${mediaPath(idx,true)}" target="_blank" rel="noopener" aria-label="${c.fullSize}" title="${c.fullSize}">${icon('expand')}</a></figcaption></figure></div>`;}
    container.innerHTML=`<dialog class="site-dialog dialog-${m.kind}" aria-labelledby="dialog-title">${common}${body}</dialog>`;const dialog=container.querySelector('dialog');dialog.addEventListener('cancel',e=>{e.preventDefault();closeDialog();});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});dialog.showModal();if(m.kind==='gallery')container.querySelector(`[data-gallery="${m.index}"]`)?.focus({preventScroll:true});
  }
  function pet() { const lines=state.lang==='zh'?['呼噜呼噜……这份温柔，我收下啦。','今天已经很努力了。休息一会儿吧。','你的每一点进步，我都有看见。']:['Purr… I’ll keep this little kindness.','You’ve done a lot. A little rest is okay.','I see every small step you take.']; const bubble=document.getElementById('hello'); if(bubble)bubble.textContent=lines[state.pets++%lines.length]; const cat=document.querySelector('.hero-cat'); if(cat&&!state.paused){cat.classList.remove('petted');void cat.offsetWidth;cat.classList.add('petted');} }
  function stopTimer(){if(state.running){state.elapsed+=Date.now()-state.startAt;state.running=false;}}
  let ignoreClick=false;
  root.addEventListener('click', e=>{ const button=e.target.closest('button'); if(!button)return; if(ignoreClick){ignoreClick=false;return;} const d=button.dataset; if(d.scene!==undefined){chooseScene(Number(d.scene));return;}
    if(d.gallery!==undefined){if(state.modal){state.modal={kind:'gallery',index:Number(d.gallery)};mountDialog();}else openDialog('gallery',Number(d.gallery));return;}
    if(d.readingChoice!==undefined){state.reading=d.readingChoice;updateReading();return;}
    if(d.insight!==undefined){state.insight=Number(d.insight);render(`[data-insight="${d.insight}"]`);return;}
    if(d.assistant!==undefined){state.assistantMode=Number(d.assistant);render(`[data-assistant="${d.assistant}"]`);return;}
    if(d.day!==undefined){state.day=Number(d.day);render(`[data-day="${d.day}"]`);return;}
    if(d.mode!==undefined){state.dayMode=Number(d.mode);render(`[data-mode="${d.mode}"]`);return;}
    if(d.task!==undefined){const i=Number(d.task);state.tasks[i]=!state.tasks[i];if(i===0&&state.tasks[i])stopTimer();render(`[data-task="${i}"]`);return;}
    if(d.gantt!==undefined){state.gantt=Number(d.gantt);render(`[data-gantt="${d.gantt}"]`);return;}
    if(d.agent!==undefined){state.agent=Number(d.agent);render(`[data-agent="${d.agent}"]`);return;}
    if(d.node!==undefined){const i=Number(d.node);if(i>0&&i<4){state.phase=i-1;render(`[data-node="${i}"]`);}return;}
    if(d.cat!==undefined){state.cat=Number(d.cat);updateCompanion();return;}
    const action=d.action;
    if(action==='home')chooseScene(0);
    if(action==='language'){state.lang=state.lang==='zh'?'en':'zh';safeWrite('mewment-language',state.lang);render('.language-switch');document.getElementById('announcer').textContent=t().nav[state.scene];}
    if(action==='motion'){state.paused=!state.paused;render('.motion-switch');}
    if(action==='pet'){pet();window.MewMotion.pet();}
    if(action==='timer'){if(state.running)stopTimer();else{state.startAt=Date.now();state.running=true;}render('[data-action="timer"]');}
    if(action==='gallery')openDialog('gallery',n().chapters[state.scene].gallery);
    if(action==='replay-demo'){state.paused=false;render();}
    if(action==='story')openDialog('story');
    if(action==='family')openDialog('family');
    if(action==='scene-info')openDialog('info');
    if(action==='close')closeDialog();
    if(action==='expand-memory'){state.expanded=!state.expanded;render('[data-action="expand-memory"]');}
    if(action==='arrange'){state.positions=defaultPositions.map(p=>({...p}));render('[data-action="arrange"]');}
    if(action==='complete-step'){state.projectDone[state.phase]=!state.projectDone[state.phase];render('[data-action="complete-step"]');}
    if(action==='next-cat'){state.cat=(state.cat+1)%4;updateCompanion();}
    if(action==='reset-day'){stopTimer();state.elapsed=0;state.tasks=[false,false,false];state.day=5;state.dayMode=0;render('[data-action="reset-day"]');}
  });
  setInterval(()=>{document.querySelectorAll('[data-timer]').forEach(el=>el.textContent=timerText());},250);
  document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select,dialog')||e.altKey||e.ctrlKey||e.metaKey)return;const node=e.target.closest('[data-node]');if(node&&['ArrowRight','ArrowLeft','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const i=Number(node.dataset.node),p=state.positions[i];p.x=Math.min(84,Math.max(16,p.x+(e.key==='ArrowRight'?2:e.key==='ArrowLeft'?-2:0)));p.y=Math.min(86,Math.max(12,p.y+(e.key==='ArrowDown'?2:e.key==='ArrowUp'?-2:0)));node.style.left=p.x+'%';node.style.top=p.y+'%';drawConnections();return;}if(e.target.closest('[role="tab"]')&&['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const tab=e.target.closest('[role="tab"]'),tabs=[...tab.closest('[role="tablist"]').querySelectorAll('[role="tab"]')],index=e.key==='Home'?0:e.key==='End'?tabs.length-1:(tabs.indexOf(tab)+(e.key==='ArrowRight'?1:tabs.length-1))%tabs.length;tabs[index].click();document.getElementById(tabs[index].id)?.focus();return;}if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();chooseScene(state.scene+(e.key==='ArrowRight'?1:-1));}});
  let drag=null;
  root.addEventListener('pointerdown',e=>{const node=e.target.closest('[data-node]');if(!node||e.button!==0)return;const board=node.closest('.project-canvas');drag={id:Number(node.dataset.node),node,rect:board.getBoundingClientRect(),x:e.clientX,y:e.clientY,moved:false};node.setPointerCapture(e.pointerId);});
  root.addEventListener('pointermove',e=>{if(!drag)return;if(Math.abs(e.clientX-drag.x)+Math.abs(e.clientY-drag.y)<5&&!drag.moved)return;drag.moved=true;const p=state.positions[drag.id];p.x=Math.max(16,Math.min(84,(e.clientX-drag.rect.left)/drag.rect.width*100));p.y=Math.max(12,Math.min(86,(e.clientY-drag.rect.top)/drag.rect.height*100));drag.node.style.left=p.x+'%';drag.node.style.top=p.y+'%';drawConnections();});
  root.addEventListener('pointerup',()=>{if(drag){ignoreClick=drag.moved;drag=null;}});
  root.addEventListener('pointercancel',()=>{drag=null;ignoreClick=false;});
  matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',event=>{state.paused=event.matches;render();});
  window.MewMotion.init({paused:()=>state.paused});
  render();
})();
